"""Generate manuscript tables, figures and number macros from results/raw.

Pure re-aggregation of existing raw records (runs no experiment).  Reuses the
helpers of scripts/summarize_first_run.py.  Outputs:

  paper/generated/*.tex         LaTeX tables, a pgfplots figure, number macros
  results/paper_assets.json     every number used by the manuscript

Quantities computed here that were NOT pre-registered (the exact squared-norm
decomposition of FR-E2, the bilinear decay-accuracy columns) are EXPLORATORY
re-aggregations of already-seen results and are labelled as such.
"""

import json
import math
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))
sys.path.insert(0, os.path.join(ROOT, "scripts"))

from summarize_first_run import factorial, load, med, mx, per_seed_slopes  # noqa: E402
from scssm.metrics import loglog_slope, median  # noqa: E402

OUT = os.path.join(ROOT, "paper", "generated")
MS = [1, 2, 4, 8]
LN2 = math.log(2.0)
VARIANT_TEX = {
    "zoh_dt": r"exact ZOH, $\Delta{=}dt\,g$",
    "eulerB_dt": r"Euler-$B$, $\Delta{=}dt\,g$",
    "bilinear_dt": r"bilinear, $\Delta{=}dt\,g$",
    "zoh_nodt": r"exact ZOH, $\Delta{=}\tau g$",
    "eulerB_nodt": r"Euler-$B$, $\Delta{=}\tau g$",
    "bilinear_nodt": r"bilinear, $\Delta{=}\tau g$",
}
ORDER = ["zoh_dt", "eulerB_dt", "bilinear_dt", "zoh_nodt", "eulerB_nodt", "bilinear_nodt"]


def sci(x, digits=2):
    """LaTeX scientific notation (math mode content)."""
    if x is None:
        return r"\text{n/a}"
    if x == 0:
        return "0"
    e = int(math.floor(math.log10(abs(x))))
    m = x / 10 ** e
    s = f"{m:.{digits - 1}f}"
    if s.startswith("10"):
        e += 1
        s = f"{m / 10:.{digits - 1}f}"
    if -2 <= e <= 2:
        dec = max(digits - 1 - e, 0)
        return f"{round(x, digits - 1 - e):.{dec}f}"
    return rf"{s}\times10^{{{e}}}"


def cell(x, digits=2):
    return f"${sci(x, digits)}$"


def write(name, text):
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, name), "w") as f:
        f.write("% AUTO-GENERATED by scripts/make_paper_assets.py from results/raw -- do not edit by hand.\n")
        f.write(text)


def main():
    A = {}  # every number used by the manuscript
    macros = {}

    # ------------------------------------------------------------------ FR-E1 (splitting)
    e1 = [r for r in load("FR-E1-SPLIT__uniform-real") if r["kind"] == "variant"]
    ref = [r for r in load("FR-E1-SPLIT__uniform-real") if r["kind"] == "reference_check"]
    rows = []
    A["E1"] = {}
    for v in ORDER:
        rv = [r for r in e1 if r["variant"] == v]
        a = {m: med([r for r in rv if r["m"] == m], "artifact_y") for m in MS}
        a8max = mx([r for r in rv if r["m"] == 8], "artifact_y")
        sl = median(per_seed_slopes(rv, "artifact_y", MS))
        A["E1"][v] = {"median_artifact": a, "max_artifact_m8": a8max, "median_slope": sl}
        rows.append(f"{VARIANT_TEX[v]} & " + " & ".join(cell(a[m]) for m in MS) +
                    f" & {cell(a8max)} & {'--' if sl is None else f'${sl:.2f}$'} \\\\")
    zmax = max(r["change_y"] for r in e1 if r["variant"] == "zoh_dt" and r["m"] > 1)
    A["E1"]["zoh_dt_max_change"] = zmax
    A["E1"]["exact_vs_rk4_max"] = max(r["exact_zoh_vs_rk4_rel_l2_y"] for r in ref)
    write("tab_split.tex", r"""\begin{table}[t]
\caption{Splitting a held interval into $m$ sub-steps (FR-E1-SPLIT; toy, 32 units, uniform base grid, real modes).
Entries are the median over units of the output artifact $\|y_m-y^\star\|_2/\|y^\star\|_2$ at the 17 common base times, where $y^\star$ is the exact held-path solution;
slope is the median per-unit log--log slope over $m\in\{1,2,4,8\}$. $\tau$ is the base step, so $\Delta{=}\tau g$ coincides with $\Delta{=}dt\,g$ at $m{=}1$.}
\label{tab:split}
\centering\small
\resizebox{\columnwidth}{!}{%
\begin{tabular}{lcccccc}
\toprule
variant & $m{=}1$ & $m{=}2$ & $m{=}4$ & $m{=}8$ & max, $m{=}8$ & slope \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}}
\end{table}
""")
    macros["EoneZohMax"] = sci(zmax)
    macros["EoneRKmax"] = sci(A["E1"]["exact_vs_rk4_max"])
    macros["EoneEulerSlope"] = f"{A['E1']['eulerB_dt']['median_slope']:.2f}"
    macros["EoneBilinSlope"] = f"{A['E1']['bilinear_dt']['median_slope']:.2f}"
    macros["EoneEulerMone"] = sci(A["E1"]["eulerB_dt"]["median_artifact"][1])
    macros["EoneEulerMeight"] = sci(A["E1"]["eulerB_dt"]["median_artifact"][8])
    macros["EoneNodtMeight"] = sci(A["E1"]["zoh_nodt"]["median_artifact"][8])
    macros["EoneNodtMtwo"] = sci(A["E1"]["zoh_nodt"]["median_artifact"][2])

    # ------------------------------------------------------------------ FR-E1 secondary configs
    A["E1_secondary"] = {}
    for tag in ("jittered-real", "uniform-complex"):
        rs = [r for r in load(f"FR-E1-SPLIT__{tag}") if r["kind"] == "variant"]
        A["E1_secondary"][tag] = {
            "zoh_dt_max_change": max(r["change_y"] for r in rs if r["variant"] == "zoh_dt" and r["m"] > 1),
            "bilinear_dt_median_change_m8": med([r for r in rs if r["variant"] == "bilinear_dt" and r["m"] == 8], "change_y"),
        }
    macros["EoneComplexBilin"] = sci(A["E1_secondary"]["uniform-complex"]["bilinear_dt_median_change_m8"])
    macros["EoneRealBilin"] = sci(med([r for r in e1 if r["variant"] == "bilinear_dt" and r["m"] == 8], "change_y"))

    # ------------------------------------------------------------------ FR-E4 stiffness (N2, N3)
    e4 = load("FR-E4-NUMERICS__scalar")
    n2 = [r for r in e4 if r["case"] == "N2_stiff"]
    rows = []
    A["N2"] = []
    for lam in (-5.0, -50.0, -500.0):
        for m in (1, 4, 16, 32):
            b = next(r for r in n2 if r["lambda"] == lam and r["m"] == m and r["variant"] == "bilinear_dt")
            e = next(r for r in n2 if r["lambda"] == lam and r["m"] == m and r["variant"] == "eulerB_dt")
            z = 0.5 / m * LN2 * lam
            exact = math.exp(z)
            rec = {"lambda": lam, "m": m, "z": z, "abar_bilinear": b["abar"], "abar_exact": exact,
                   "decay_error": abs(b["abar"] - exact), "stable": abs(b["abar"]) < 1.0,
                   "sign_alternating": b["abar"] < 0, "artifact_bilinear": b["artifact_y"], "artifact_eulerB": e["artifact_y"]}
            A["N2"].append(rec)
            rows.append(f"${lam:g}$ & ${m}$ & ${z:.2f}$ & ${b['abar']:+.3f}$ & {cell(exact)} & "
                        f"{'yes' if rec['stable'] else 'no'} & {'yes' if rec['sign_alternating'] else 'no'} & "
                        f"{cell(b['artifact_y'])} & {cell(e['artifact_y'])} \\\\")
    n3 = [r for r in e4 if r["case"] == "N3_coarse_steady_state"]
    A["N3"] = {f"{r['variant']}@{r['dt']}": r["rel_err"] for r in n3}
    n3rows = []
    for dt in (0.01, 0.5, 8.0):
        g = {r["variant"]: r["rel_err"] for r in n3 if r["dt"] == dt}
        n3rows.append(f"${dt:g}$ & {cell(g['zoh_dt'])} & {cell(g['eulerB_dt'])} & {cell(g['bilinear_dt'])} \\\\")
    write("tab_stiff.tex", r"""\begin{table}[t]
\caption{Stiff scalar mode (FR-E4-N2; $g{=}\ln 2$, base step $0.5$, held sine input). Bilinear is stable ($|\bar A|<1$) for every step, but for $z{=}\Delta\lambda<-2$ its transition is negative
(sign-alternating transients) and tends to $-1$, whereas the exact decay $e^{z}$ tends to $0$. The last two columns are the output artifact against exact ZOH.
The stable/sign/decay columns are an exploratory re-reading of logged values.}
\label{tab:stiff}
\centering\small
\resizebox{\columnwidth}{!}{%
\begin{tabular}{rrrrrccrr}
\toprule
$\lambda$ & $m$ & $z$ & $\bar A_{\mathrm{bil}}$ & $e^{z}$ & stable & sign-alt. & bilinear & Euler-$B$ \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}}
\vspace{4pt}

\begin{tabular}{rccc}
\toprule
$dt$ & exact ZOH & Euler-$B$ & bilinear \\
\midrule
""" + "\n".join(n3rows) + r"""
\bottomrule
\end{tabular}
\vspace{2pt}

{\footnotesize Lower block (FR-E4-N3): relative steady-state error under a held unit input, $\lambda{=}-1$.}
\end{table}
""")
    b500 = next(r for r in A["N2"] if r["lambda"] == -500.0 and r["m"] == 1)
    macros["NtwoAbar"] = f"{b500['abar_bilinear']:.3f}"
    macros["NtwoBilArt"] = sci(b500["artifact_bilinear"])
    macros["NtwoEulerArt"] = sci(b500["artifact_eulerB"])
    macros["NthreeEulerSmall"] = sci(A["N3"]["eulerB_dt@0.01"])
    macros["NthreeEulerLarge"] = sci(A["N3"]["eulerB_dt@8.0"])

    # ------------------------------------------------------------------ FR-E3 readouts
    e3 = load("FR-E3-READOUT__uniform-real")
    ra = [r for r in e3 if r["scenario"] == "a_split_nonuniform"]
    rb = [r for r in e3 if r["scenario"] == "b_newobs_nonuniform"]
    names = [("last", "last sample"), ("sample_sum", "sample sum"), ("sample_mean", "sample mean"),
             ("time_riemann", r"right-endpoint $\sum y_k\,dt_k$"), ("time_trapz", "trapezoidal endpoint sum"),
             ("time_exact", "exact held-path integral")]
    rows = []
    A["E3a"] = {}
    A["E3b"] = {}
    for key, label in names:
        cz = med([r for r in ra if r["variant"] == "zoh_dt" and r["m"] == 8], "change_" + key)
        ce = med([r for r in ra if r["variant"] == "eulerB_nodt" and r["m"] == 8], "change_" + key)
        if key == "sample_sum":
            eb1 = eb8 = None
        elif key == "last":
            eb1 = med([r for r in rb if r["variant"] == "zoh_dt" and r["m"] == 1], "err_truth_last")
            eb8 = med([r for r in rb if r["variant"] == "zoh_dt" and r["m"] == 8], "err_truth_last")
        else:
            eb1 = med([r for r in rb if r["variant"] == "zoh_dt" and r["m"] == 1], "err_truth_" + key)
            eb8 = med([r for r in rb if r["variant"] == "zoh_dt" and r["m"] == 8], "err_truth_" + key)
        A["E3a"][key] = {"zoh_dt_change_m8": cz, "eulerB_nodt_change_m8": ce}
        A["E3b"][key] = {"zoh_dt_err_m1": eb1, "zoh_dt_err_m8": eb8}
        ecell = "--" if eb1 is None else f"{cell(eb1)}$\\to${cell(eb8)}"
        rows.append(f"{label} & {cell(cz)} & {'n/a' if ce is None else cell(ce)} & {ecell} \\\\")
    rme = median(per_seed_slopes([r for r in ra if r["variant"] == "zoh_dt"], "riemann_minus_exact", MS))
    neg = sum(1 for s in per_seed_slopes([r for r in ra if r["variant"] == "zoh_dt"], "riemann_minus_exact", MS) if s is not None and s < 0)
    A["E3a"]["riemann_minus_exact_median_slope"] = rme
    A["E3a"]["riemann_minus_exact_n_negative"] = neg
    write("tab_readout.tex", r"""\begin{table}[t]
\caption{Readouts under a density change (FR-E3-READOUT; toy, 32 units). Columns 2--3: scale-normalized change $|r_8-r_1|/s$ when only the first half of the base intervals is split into $8$ held sub-steps
(physical path unchanged); $s$ is the RMS base-time output at $m{=}1$ ($\times K_1$ for the sample sum). Column 4: scale-normalized error to the continuous-time truth when new observations are added to the first half only, $m{=}1\to8$.
Medians over units. The exact held-path integral is defined only for exact-ZOH states.}
\label{tab:readout}
\centering\small
\resizebox{\columnwidth}{!}{%
\begin{tabular}{lccc}
\toprule
readout & split, exact ZOH $\Delta{=}dt\,g$ & split, Euler-$B$ $\Delta{=}\tau g$ & new obs., exact ZOH \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}}
\end{table}
""")
    macros["EthreeMeanChange"] = sci(A["E3a"]["sample_mean"]["zoh_dt_change_m8"])
    macros["EthreeSumChange"] = sci(A["E3a"]["sample_sum"]["zoh_dt_change_m8"])
    macros["EthreeTrapzChange"] = sci(A["E3a"]["time_trapz"]["zoh_dt_change_m8"])
    macros["EthreeRiemannChange"] = sci(A["E3a"]["time_riemann"]["zoh_dt_change_m8"])
    macros["EthreeExactChange"] = sci(A["E3a"]["time_exact"]["zoh_dt_change_m8"])
    macros["EthreeMeanErrOne"] = sci(A["E3b"]["sample_mean"]["zoh_dt_err_m1"])
    macros["EthreeMeanErrEight"] = sci(A["E3b"]["sample_mean"]["zoh_dt_err_m8"])
    macros["EthreeExactErrEight"] = sci(A["E3b"]["time_exact"]["zoh_dt_err_m8"])
    macros["EthreeRMEslope"] = f"{rme:.3f}"
    macros["EthreeRMEneg"] = str(neg)

    # ------------------------------------------------------------------ fix interaction
    _, fac = factorial(e3)
    A["factorial"] = fac
    labels = [
        r"none ($\Delta{=}\tau g$, Euler-$B$, sample mean)",
        r"time readout only (trapezoidal)",
        r"exact ZOH $B$ only",
        r"$\Delta{=}dt\,g$ only",
        r"$\Delta{=}dt\,g$ + trapezoidal",
        r"$\Delta{=}dt\,g$ + exact ZOH (sample mean)",
        r"$\Delta{=}dt\,g$ + exact ZOH + trapezoidal",
        r"$\Delta{=}dt\,g$ + exact ZOH + exact integral",
    ]
    rows = [f"{lab} & {cell(f['median_change_m8'])} \\\\" for lab, f in zip(labels, fac)]
    write("tab_interaction.tex", r"""\begin{table}[t]
\caption{One fix at a time (FR-E3-READOUT, split of the first half, $m{=}8$; median scale-normalized readout change over 32 units). The effects are not additive,
so no per-fix share is reported.}
\label{tab:interaction}
\centering\small
\begin{tabular}{lc}
\toprule
fixes applied & change \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
""")
    for i, key in enumerate(["FacNone", "FacTime", "FacZoh", "FacDt", "FacDtTime", "FacDtZoh", "FacDtZohTime", "FacAll"]):
        macros[key] = sci(fac[i]["median_change_m8"])

    # ------------------------------------------------------------------ FR-E2 exact decomposition (EXPLORATORY)
    e2 = [r for r in load("FR-E2-NEWOBS__uniform-real") if r["kind"] == "variant"]
    ybase = {(r["seed"], r["variant"], r["m"]): r["y_base"] for r in e2}
    art_zoh = mx([r for r in e2 if r["variant"] == "zoh_dt"], "artifact")
    seeds = sorted({r["seed"] for r in e2})
    rows = []
    A["E2"] = {"zoh_dt_max_artifact_vs_rk4": art_zoh, "decomposition": {}}
    for v in ORDER:
        for m in (2, 8):
            sp = sa = sc = st = 0.0
            cross_frac = []
            for s in seeds:
                P = [x - y for x, y in zip(ybase[(s, "zoh_dt", m)], ybase[(s, "zoh_dt", 1)])]
                Tt = [x - y for x, y in zip(ybase[(s, v, m)], ybase[(s, v, 1)])]
                R = [t - p for t, p in zip(Tt, P)]
                pp = sum(x * x for x in P)
                rr = sum(x * x for x in R)
                pr = sum(x * y for x, y in zip(P, R))
                tt = sum(x * x for x in Tt)
                sp, sa, sc, st = sp + pp, sa + rr, sc + 2 * pr, st + tt
                if tt > 0:
                    cross_frac.append(2 * pr / tt)
            tot_med = med([r for r in e2 if r["variant"] == v and r["m"] == m], "total_change")
            d = {"pooled_path_frac": sp / st, "pooled_artifact_frac": sa / st, "pooled_cross_frac": sc / st,
                 "cross_frac_min": min(cross_frac), "cross_frac_max": max(cross_frac), "median_total_change": tot_med}
            A["E2"]["decomposition"][f"{v}@{m}"] = d
            if v == "zoh_dt":
                rows.append(f"{VARIANT_TEX[v]} & ${m}$ & {cell(tot_med)} & \\multicolumn{{4}}{{c}}{{artifact $\\le{sci(art_zoh)}$ vs.\\ RK4 (proxy reference)}} \\\\")
            else:
                rows.append(f"{VARIANT_TEX[v]} & ${m}$ & {cell(tot_med)} & ${d['pooled_path_frac']:.3f}$ & ${d['pooled_artifact_frac']:.3f}$ & "
                            f"${d['pooled_cross_frac']:+.3f}$ & $[{d['cross_frac_min']:+.2f},{d['cross_frac_max']:+.2f}]$ \\\\")
    write("tab_newobs.tex", r"""\begin{table}[t]
\caption{Adding new observations of the same signal (FR-E2-NEWOBS; toy, 32 units). The change $T=y_m-y_1$ at base times splits \emph{exactly} as $T=P+R$, where $P$ is the change of the continuous-time solution on the new held path
(genuine new external information) and $R$ is the change of the discretization artifact. Hence $\|T\|^2=\|P\|^2+\|R\|^2+2\langle P,R\rangle$; we report these three terms as fractions of $\sum_{\text{units}}\|T\|^2$ (they sum to 1)
and the per-unit range of the cross fraction. $P$ uses the exact-ZOH output as a proxy for the continuous-time held-path solution (validated against RK4 to the bound shown).
Median total change is relative to $\|y_1\|$. EXPLORATORY re-aggregation; the cross term shows that no per-unit ``share'' is well defined.}
\label{tab:newobs}
\centering\small
\resizebox{\columnwidth}{!}{%
\begin{tabular}{lcccccc}
\toprule
variant & $m$ & median $\|T\|/\|y_1\|$ & $\|P\|^2$ & $\|R\|^2$ & $2\langle P,R\rangle$ & cross range \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}}
\end{table}
""")
    macros["EtwoZohArt"] = sci(art_zoh)
    decs = [d for k, d in A["E2"]["decomposition"].items() if not k.startswith("zoh_dt@")]
    macros["EtwoCrossMin"] = f"{min(d['cross_frac_min'] for d in decs):+.2f}"
    macros["EtwoCrossMax"] = f"{max(d['cross_frac_max'] for d in decs):+.2f}"
    dn = A["E2"]["decomposition"]["zoh_nodt@8"]
    macros["EtwoNodtArtFrac"] = f"{dn['pooled_artifact_frac']:.2f}"
    macros["EtwoNodtCrossFrac"] = f"{dn['pooled_cross_frac']:+.2f}"
    de = A["E2"]["decomposition"]["eulerB_dt@8"]
    macros["EtwoEulerArtFrac"] = f"{de['pooled_artifact_frac']:.2f}"
    macros["EtwoEulerCrossFrac"] = f"{de['pooled_cross_frac']:+.2f}"
    e2ref = [r for r in load("FR-E2-NEWOBS__uniform-real") if r["kind"] == "reference"]
    macros["EtwoHoldErrOne"] = sci(med([r for r in e2ref if r["m"] == 1], "ct_held_err_to_truth"))
    macros["EtwoHoldErrEight"] = sci(med([r for r in e2ref if r["m"] == 8], "ct_held_err_to_truth"))
    macros["EtwoSlope"] = f"{median(per_seed_slopes([r for r in e2 if r['variant'] == 'zoh_dt'], 'err_to_truth', MS)):.2f}"

    # ------------------------------------------------------------------ P1-COMP-01 coupling
    comp = load("P1-COMP-01")
    rows = []
    A["COMP01"] = {}
    for case, lab in (("distinct", r"$a{=}1,\;c{=}0.5$"), ("equal", r"$a{=}c{=}1$")):
        rc = [r for r in comp if r["case"] == case]
        err = {r["m"]: r["layerwise_error"] for r in rc}
        chg = {r["m"]: r["layerwise_change"] for r in rc}
        inv = max(r["coupled_invariance"] for r in rc if r["m"] > 1)
        rk = max(r["coupled_vs_rk4"] for r in rc)
        sl = loglog_slope(MS, [err[m] for m in MS])
        A["COMP01"][case] = {"layerwise_error": err, "layerwise_change": chg, "coupled_invariance_max": inv,
                             "coupled_vs_rk4_max": rk, "slope": sl}
        rows.append(f"{lab} & " + " & ".join(cell(err[m]) for m in MS) + f" & ${sl:.2f}$ & {cell(chg[8])} & {cell(inv)} \\\\")
    write("tab_coupling.tex", r"""\begin{table}[t]
\caption{Two-layer linear cascade $\dot h_1=-ah_1+bu$, $\dot h_2=-ch_2+dh_1$ under interval splitting (P1-COMP-01; $b{=}d{=}1$; held input of FIRST\_RUN unit 0).
Columns $m$: error of the layerwise computation (layer 2 holds the layer-1 endpoint value) against the exact coupled solution, $\|h_2^{\mathrm{lw}}-h_2\|/\|h_2\|$ over base times.
``change'' is the layerwise change $m{=}8$ vs.\ $m{=}1$; the last column is the largest change of the exact coupled solution over $m$. No external observation is added in this experiment.}
\label{tab:coupling}
\centering\small
\resizebox{\columnwidth}{!}{%
\begin{tabular}{lccccccc}
\toprule
case & $m{=}1$ & $m{=}2$ & $m{=}4$ & $m{=}8$ & slope & change & exact inv. \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}}
\end{table}
""")
    macros["CompErrOne"] = sci(A["COMP01"]["distinct"]["layerwise_error"][1])
    macros["CompErrEight"] = sci(A["COMP01"]["distinct"]["layerwise_error"][8])
    macros["CompSlope"] = f"{A['COMP01']['distinct']['slope']:.2f}"
    macros["CompSlopeEq"] = f"{A['COMP01']['equal']['slope']:.2f}"
    macros["CompInv"] = sci(max(A["COMP01"][c]["coupled_invariance_max"] for c in A["COMP01"]))
    macros["CompRK"] = sci(max(A["COMP01"][c]["coupled_vs_rk4_max"] for c in A["COMP01"]))

    # ------------------------------------------------------------------ numerics floor (appendix)
    n1 = [r for r in e4 if r["case"] == "N1_cancellation"]
    n1b = [r for r in e4 if r["case"] == "N1b_split_drift_fp64"]
    n4 = [r for r in e4 if r["case"] == "N4_split_drift_fp32_emulated"]
    rows1 = [f"{cell(r['z'], 1)} & {cell(r['rel_err_naive'])} & {cell(r['rel_err_expm1'])} \\\\" for r in n1]
    ms4 = sorted({r["m"] for r in n4})
    rows4 = []
    for m in ms4:
        f64 = {r["formula"]: r["rel_err_h1"] for r in n1b if r["m"] == m}
        f32 = {r["formula"]: r["rel_err_h1"] for r in n4 if r["m"] == m}
        rows4.append(f"${m}$ & {cell(f64.get('expm1'))} & {cell(f32.get('expm1'))} & {cell(f32.get('naive'))} \\\\")
    A["N1"] = n1
    A["N4"] = {m: {r["formula"]: r["rel_err_h1"] for r in n4 if r["m"] == m} for m in ms4}
    write("tab_numerics.tex", r"""\begin{table}[h]
\caption{Numerical floor (FR-E4). Left: relative error of the ZOH input coefficient $(e^{z}-1)/\lambda$ against a 50-digit reference. Right: splitting $[0,1]$ into $m$ held sub-steps
($\lambda{=}-1$, $g{=}\ln2$, exact $h(1)=0.5$); float32 is an \emph{emulation} (every primitive rounded, correctly rounded $\exp$), not a GPU kernel.}
\label{tab:numerics}
\centering\small
\begin{tabular}{rcc}
\toprule
$z$ & naive & \texttt{expm1} \\
\midrule
""" + "\n".join(rows1) + r"""
\bottomrule
\end{tabular}\hspace{1em}
\begin{tabular}{rccc}
\toprule
$m$ & fp64 \texttt{expm1} & fp32 \texttt{expm1} & fp32 naive \\
\midrule
""" + "\n".join(rows4) + r"""
\bottomrule
\end{tabular}
\end{table}
""")
    macros["NfourFloor"] = sci(A["N4"][16384]["expm1"])
    macros["NoneNaive"] = sci(next(r["rel_err_naive"] for r in n1 if abs(r["z"] + 1e-14) < 1e-20))

    # ------------------------------------------------------------------ hypothesis verdicts (appendix; not a results table)
    hyp = json.load(open(os.path.join(ROOT, "results", "raw", "hypotheses.json")))
    chyp = json.load(open(os.path.join(ROOT, "results", "raw", "P1-COMP-01__hypotheses.json")))
    rows = [f"FIRST\\_RUN & {h['id'].replace('_', chr(92) + '_')} & {h['status']} \\\\" for h in hyp["hypotheses"]]
    rows += [f"P1-COMP-01 & {h['id']} ({h['case']}) & {h['status']} \\\\" for h in chyp["hypotheses"]]
    A["hypotheses"] = {"FIRST_RUN": {h["id"]: h["status"] for h in hyp["hypotheses"]},
                       "P1-COMP-01": {f"{h['id']}:{h['case']}": h["status"] for h in chyp["hypotheses"]}}
    write("tab_hypotheses.tex", r"""\begin{table}[h]
\caption{Pre-registered check verdicts, including the failed H7c\_original (mis-specified before the run; amendment A2) and the weakly supported H7c\_restated. These are bookkeeping, not scientific results.}
\label{tab:hypotheses}
\centering\small
\begin{tabular}{llc}
\toprule
run & check & verdict \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
""")

    # ------------------------------------------------------------------ figure (pgfplots): convergence
    # Palette slots 1-3 of the dataviz reference palette (validated, light mode);
    # every series also has a distinct marker and dash pattern (not color alone).
    def coords(series):
        return " ".join(f"({m},{y:.6e})" for m, y in series if y and y > 0)

    s_eu = [(m, A["E1"]["eulerB_dt"]["median_artifact"][m]) for m in MS]
    s_bi = [(m, A["E1"]["bilinear_dt"]["median_artifact"][m]) for m in MS]
    s_nd = [(m, A["E1"]["zoh_nodt"]["median_artifact"][m]) for m in MS]
    s_cd = [(m, A["COMP01"]["distinct"]["layerwise_error"][m]) for m in MS]
    s_ce = [(m, A["COMP01"]["equal"]["layerwise_error"][m]) for m in MS]
    write("fig_convergence.tex", r"""\begin{figure}[t]
\centering
\definecolor{seriesA}{HTML}{2A78D6}\definecolor{seriesB}{HTML}{EB6834}\definecolor{seriesC}{HTML}{1BAF7A}
\begin{tikzpicture}
\begin{groupplot}[group style={group size=2 by 1, horizontal sep=1.3cm},
  width=0.54\columnwidth, height=0.5\columnwidth, xmode=log, ymode=log, log basis x=2,
  xtick={1,2,4,8}, xticklabels={1,2,4,8}, xlabel={sub-steps $m$}, tick label style={font=\scriptsize},
  label style={font=\scriptsize}, title style={font=\scriptsize}, grid=major, grid style={gray!20, line width=0.3pt},
  axis line style={gray!60}, legend style={font=\tiny, draw=none, fill=none}, legend cell align=left]
\nextgroupplot[title={(a) single layer, FR-E1}, ylabel={relative error}, legend pos=south west, ymin=5e-5, ymax=5]
\addplot[seriesA, line width=1pt, mark=*, mark size=1.6pt] coordinates {""" + coords(s_eu) + r"""};
\addlegendentry{Euler-$B$, $\Delta{=}dt\,g$}
\addplot[seriesB, line width=1pt, dashed, mark=square*, mark size=1.6pt] coordinates {""" + coords(s_bi) + r"""};
\addlegendentry{bilinear, $\Delta{=}dt\,g$}
\addplot[seriesC, line width=1pt, dotted, mark=triangle*, mark size=2pt] coordinates {""" + coords(s_nd) + r"""};
\addlegendentry{exact ZOH, $\Delta{=}\tau g$}
\nextgroupplot[title={(b) two-layer cascade, P1-COMP-01}, legend pos=south west, ymin=5e-3, ymax=0.5]
\addplot[seriesA, line width=1pt, mark=*, mark size=1.6pt] coordinates {""" + coords(s_cd) + r"""};
\addlegendentry{$a{=}1,\,c{=}0.5$}
\addplot[seriesB, line width=1pt, dashed, mark=square*, mark size=1.6pt] coordinates {""" + coords(s_ce) + r"""};
\addlegendentry{$a{=}c{=}1$}
\end{groupplot}
\end{tikzpicture}
\caption{Error against the exact held-path solution as the same held interval is split into $m$ sub-steps (medians over 32 toy units in (a); one deterministic case per line in (b)).
Exact ZOH with $\Delta{=}dt\,g$ (a) and the exact coupled solution (b) stay at $10^{-15}$ and are not drawn. The $\Delta{=}\tau g$ line starts at $m{=}2$ because it is exact at $m{=}1$ by construction.
Values are listed in \cref{tab:split,tab:coupling}.}
\label{fig:convergence}
\end{figure}
""")

    # ------------------------------------------------------------------ hypothesis evidence used in the text
    hv = {h["id"]: h for h in hyp["hypotheses"]}
    macros["HsevenOrigSlope"] = f"{hv['H7c_original']['evidence']['median_slope_change_time_riemann_m2_m8']:+.2f}"
    macros["HfourEulerFrac"] = f"{round(hv['H4']['evidence']['eulerB_nodt']['frac_nondecreasing_m2_to_m8'] * 32)}"
    macros["NunitsPrimary"] = str(len(seeds))
    fr_man = json.load(open(os.path.join(ROOT, "run_manifest.json")))
    macros["FirstRunSeconds"] = f"{fr_man['wall_clock_seconds']:.1f}"
    macros["CompSeconds"] = f"{fr_man['subsequent_runs'][0]['wall_clock_seconds']:.2f}"

    # ------------------------------------------------------------------ macros + json
    lines = [f"\\newcommand{{\\{k}}}{{\\ensuremath{{{v}}}}}" for k, v in sorted(macros.items())]
    write("numbers.tex", "\n".join(lines) + "\n")
    with open(os.path.join(ROOT, "results", "paper_assets.json"), "w") as f:
        json.dump(A, f, indent=1, default=str)


if __name__ == "__main__":
    main()
