"""Generate manuscript tables, figures and number macros from results/raw.

Pure re-aggregation of existing raw records (runs no experiment).  Reuses the
helpers of scripts/summarize_first_run.py.  Outputs:

  paper/generated/*.tex         LaTeX tables, a pgfplots figure, number macros
  results/paper_assets.json     every number used by the manuscript

Quantities computed here that were NOT pre-registered (the exact squared-norm
decomposition of FR-E2, the bilinear decay-accuracy columns) are EXPLORATORY
re-aggregations of already-seen results and are labelled as such.
"""

import json
import math
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))
sys.path.insert(0, os.path.join(ROOT, "scripts"))

from summarize_first_run import factorial, load, med, mx, per_seed_slopes  # noqa: E402
from scssm.metrics import loglog_slope, median  # noqa: E402

OUT = os.path.join(ROOT, "paper", "generated")
MS = [1, 2, 4, 8]
LN2 = math.log(2.0)
VARIANT_TEX = {
    "zoh_dt": r"exact ZOH, $\Delta{=}dt\,g$",
    "eulerB_dt": r"Euler-$B$, $\Delta{=}dt\,g$",
    "bilinear_dt": r"bilinear, $\Delta{=}dt\,g$",
    "zoh_nodt": r"exact ZOH, $\Delta{=}\tau g$",
    "eulerB_nodt": r"Euler-$B$, $\Delta{=}\tau g$",
    "bilinear_nodt": r"bilinear, $\Delta{=}\tau g$",
}
ORDER = ["zoh_dt", "eulerB_dt", "bilinear_dt", "zoh_nodt", "eulerB_nodt", "bilinear_nodt"]


def sci(x, digits=2):
    """LaTeX scientific notation (math mode content)."""
    if x is None:
        return r"\text{n/a}"
    if x == 0:
        return "0"
    e = int(math.floor(math.log10(abs(x))))
    m = x / 10 ** e
    s = f"{m:.{digits - 1}f}"
    if s.startswith("10"):
        e += 1
        s = f"{m / 10:.{digits - 1}f}"
    if -2 <= e <= 2:
        dec = max(digits - 1 - e, 0)
        return f"{round(x, digits - 1 - e):.{dec}f}"
    return rf"{s}\times10^{{{e}}}"


def sci3(x):
    return sci(x, 3)


def cell(x, digits=2):
    return f"${sci(x, digits)}$"


def write(name, text):
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, name), "w") as f:
        f.write("% AUTO-GENERATED by scripts/make_paper_assets.py from results/raw -- do not edit by hand.\n")
        f.write(text)


def main():
    A = {}  # every number used by the manuscript
    macros = {}

    # ------------------------------------------------------------------ FR-E1 (splitting)
    e1 = [r for r in load("FR-E1-SPLIT__uniform-real") if r["kind"] == "variant"]
    ref = [r for r in load("FR-E1-SPLIT__uniform-real") if r["kind"] == "reference_check"]
    rows = []
    A["E1"] = {}
    for v in ORDER:
        rv = [r for r in e1 if r["variant"] == v]
        a = {m: med([r for r in rv if r["m"] == m], "artifact_y") for m in MS}
        a8max = mx([r for r in rv if r["m"] == 8], "artifact_y")
        sl = median(per_seed_slopes(rv, "artifact_y", MS))
        A["E1"][v] = {"median_artifact": a, "max_artifact_m8": a8max, "median_slope": sl}
        rows.append(f"{VARIANT_TEX[v]} & " + " & ".join(cell(a[m]) for m in MS) +
                    f" & {cell(a8max)} & {'--' if sl is None else f'${sl:.2f}$'} \\\\")
    zmax = max(r["change_y"] for r in e1 if r["variant"] == "zoh_dt" and r["m"] > 1)
    A["E1"]["zoh_dt_max_change"] = zmax
    A["E1"]["exact_vs_rk4_max"] = max(r["exact_zoh_vs_rk4_rel_l2_y"] for r in ref)
    write("tab_split.tex", r"""\begin{table}[t]
\caption{Splitting a held interval into $m$ sub-steps (FR-E1-SPLIT; toy, 32 units, uniform base grid, real modes).
Entries are the median over units of the output artifact $\|y_m-y^\star\|_2/\|y^\star\|_2$ at the 17 common base times, where $y^\star$ is the exact held-path solution;
slope is the median per-unit log--log slope over $m\in\{1,2,4,8\}$. $\tau$ is the base step, so $\Delta{=}\tau g$ coincides with $\Delta{=}dt\,g$ at $m{=}1$.}
\label{tab:split}
\centering\small
\begin{tabular}{lcccccc}
\toprule
variant & $m{=}1$ & $m{=}2$ & $m{=}4$ & $m{=}8$ & max, $m{=}8$ & slope \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
""")
    macros["EoneZohMax"] = sci(zmax)
    macros["EoneRKmax"] = sci(A["E1"]["exact_vs_rk4_max"])
    macros["EoneEulerSlope"] = f"{A['E1']['eulerB_dt']['median_slope']:.2f}"
    macros["EoneBilinSlope"] = f"{A['E1']['bilinear_dt']['median_slope']:.2f}"
    macros["EoneEulerMone"] = sci(A["E1"]["eulerB_dt"]["median_artifact"][1])
    macros["EoneEulerMeight"] = sci(A["E1"]["eulerB_dt"]["median_artifact"][8])
    macros["EoneNodtMeight"] = sci(A["E1"]["zoh_nodt"]["median_artifact"][8])
    macros["EoneNodtMtwo"] = sci(A["E1"]["zoh_nodt"]["median_artifact"][2])

    # ------------------------------------------------------------------ FR-E1 secondary configs
    A["E1_secondary"] = {}
    for tag in ("jittered-real", "uniform-complex"):
        rs = [r for r in load(f"FR-E1-SPLIT__{tag}") if r["kind"] == "variant"]
        A["E1_secondary"][tag] = {
            "zoh_dt_max_change": max(r["change_y"] for r in rs if r["variant"] == "zoh_dt" and r["m"] > 1),
            "bilinear_dt_median_change_m8": med([r for r in rs if r["variant"] == "bilinear_dt" and r["m"] == 8], "change_y"),
        }
    macros["EoneComplexBilin"] = sci(A["E1_secondary"]["uniform-complex"]["bilinear_dt_median_change_m8"])
    macros["EoneRealBilin"] = sci(med([r for r in e1 if r["variant"] == "bilinear_dt" and r["m"] == 8], "change_y"))

    # ------------------------------------------------------------------ FR-E4 stiffness (N2, N3)
    e4 = load("FR-E4-NUMERICS__scalar")
    n2 = [r for r in e4 if r["case"] == "N2_stiff"]
    rows = []
    A["N2"] = []
    for lam in (-5.0, -50.0, -500.0):
        for m in (1, 4, 16, 32):
            b = next(r for r in n2 if r["lambda"] == lam and r["m"] == m and r["variant"] == "bilinear_dt")
            e = next(r for r in n2 if r["lambda"] == lam and r["m"] == m and r["variant"] == "eulerB_dt")
            z = 0.5 / m * LN2 * lam
            exact = math.exp(z)
            rec = {"lambda": lam, "m": m, "z": z, "abar_bilinear": b["abar"], "abar_exact": exact,
                   "decay_error": abs(b["abar"] - exact), "stable": abs(b["abar"]) < 1.0,
                   "sign_alternating": b["abar"] < 0, "artifact_bilinear": b["artifact_y"], "artifact_eulerB": e["artifact_y"]}
            A["N2"].append(rec)
            rows.append(f"${lam:g}$ & ${m}$ & ${z:.2f}$ & ${b['abar']:+.3f}$ & {cell(exact)} & "
                        f"{'yes' if rec['stable'] else 'no'} & {'yes' if rec['sign_alternating'] else 'no'} & "
                        f"{cell(b['artifact_y'])} & {cell(e['artifact_y'])} \\\\")
    n3 = [r for r in e4 if r["case"] == "N3_coarse_steady_state"]
    A["N3"] = {f"{r['variant']}@{r['dt']}": r["rel_err"] for r in n3}
    n3rows = []
    for dt in (0.01, 0.5, 8.0):
        g = {r["variant"]: r["rel_err"] for r in n3 if r["dt"] == dt}
        n3rows.append(f"${dt:g}$ & {cell(g['zoh_dt'])} & {cell(g['eulerB_dt'])} & {cell(g['bilinear_dt'])} \\\\")
    write("tab_stiff.tex", r"""\begin{table}[t]
\caption{Stiff scalar mode (FR-E4-N2; $g{=}\ln 2$, base step $0.5$, held sine input). Bilinear is stable ($|\bar A|<1$) for every step, but for $z{=}\Delta\lambda<-2$ its transition is negative
(sign-alternating transients) and tends to $-1$, whereas the exact decay $e^{z}$ tends to $0$. The last two columns are the output artifact against exact ZOH.
The stable/sign/decay columns are an exploratory re-reading of logged values.}
\label{tab:stiff}
\centering\small
\begin{tabular}{rrrrrccrr}
\toprule
$\lambda$ & $m$ & $z$ & $\bar A_{\mathrm{bil}}$ & $e^{z}$ & stable & sign-alt. & bilinear & Euler-$B$ \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\vspace{4pt}

\begin{tabular}{rccc}
\toprule
$dt$ & exact ZOH & Euler-$B$ & bilinear \\
\midrule
""" + "\n".join(n3rows) + r"""
\bottomrule
\end{tabular}
\vspace{2pt}

{\footnotesize Lower block (FR-E4-N3): relative steady-state error under a held unit input, $\lambda{=}-1$.}
\end{table}
""")
    b500 = next(r for r in A["N2"] if r["lambda"] == -500.0 and r["m"] == 1)
    macros["NtwoAbar"] = f"{b500['abar_bilinear']:.3f}"
    macros["NtwoBilArt"] = sci(b500["artifact_bilinear"])
    macros["NtwoEulerArt"] = sci(b500["artifact_eulerB"])
    macros["NthreeEulerSmall"] = sci(A["N3"]["eulerB_dt@0.01"])
    macros["NthreeEulerLarge"] = sci(A["N3"]["eulerB_dt@8.0"])

    # ------------------------------------------------------------------ FR-E3 readouts
    e3 = load("FR-E3-READOUT__uniform-real")
    ra = [r for r in e3 if r["scenario"] == "a_split_nonuniform"]
    rb = [r for r in e3 if r["scenario"] == "b_newobs_nonuniform"]
    names = [("last", "last sample"), ("sample_sum", "sample sum"), ("sample_mean", "sample mean"),
             ("time_riemann", r"right-endpoint $\sum y_k\,dt_k$"), ("time_trapz", "trapezoidal endpoint sum"),
             ("time_exact", "exact held-path integral")]
    rows = []
    A["E3a"] = {}
    A["E3b"] = {}
    for key, label in names:
        cz = med([r for r in ra if r["variant"] == "zoh_dt" and r["m"] == 8], "change_" + key)
        ce = med([r for r in ra if r["variant"] == "eulerB_nodt" and r["m"] == 8], "change_" + key)
        if key == "sample_sum":
            eb1 = eb8 = None
        elif key == "last":
            eb1 = med([r for r in rb if r["variant"] == "zoh_dt" and r["m"] == 1], "err_truth_last")
            eb8 = med([r for r in rb if r["variant"] == "zoh_dt" and r["m"] == 8], "err_truth_last")
        else:
            eb1 = med([r for r in rb if r["variant"] == "zoh_dt" and r["m"] == 1], "err_truth_" + key)
            eb8 = med([r for r in rb if r["variant"] == "zoh_dt" and r["m"] == 8], "err_truth_" + key)
        A["E3a"][key] = {"zoh_dt_change_m8": cz, "eulerB_nodt_change_m8": ce}
        A["E3b"][key] = {"zoh_dt_err_m1": eb1, "zoh_dt_err_m8": eb8}
        ecell = "--" if eb1 is None else f"{cell(eb1)}$\\to${cell(eb8)}"
        rows.append(f"{label} & {cell(cz)} & {'n/a' if ce is None else cell(ce)} & {ecell} \\\\")
    rme = median(per_seed_slopes([r for r in ra if r["variant"] == "zoh_dt"], "riemann_minus_exact", MS))
    neg = sum(1 for s in per_seed_slopes([r for r in ra if r["variant"] == "zoh_dt"], "riemann_minus_exact", MS) if s is not None and s < 0)
    A["E3a"]["riemann_minus_exact_median_slope"] = rme
    A["E3a"]["riemann_minus_exact_n_negative"] = neg
    write("tab_readout.tex", r"""\begin{table}[t]
\caption{Readouts under a density change (FR-E3-READOUT; toy, 32 units). Columns 2--3: scale-normalized change $|r_8-r_1|/s$ when only the first half of the base intervals is split into $8$ held sub-steps
(physical path unchanged); $s$ is the RMS base-time output at $m{=}1$ ($\times K_1$ for the sample sum). Column 4: scale-normalized error to the continuous-time truth when new observations are added to the first half only, $m{=}1\to8$.
Medians over units. The exact held-path integral is defined only for exact-ZOH states.}
\label{tab:readout}
\centering\small
\begin{tabular}{lccc}
\toprule
readout & split, exact ZOH $\Delta{=}dt\,g$ & split, Euler-$B$ $\Delta{=}\tau g$ & new obs., exact ZOH \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
""")
    macros["EthreeMeanChange"] = sci(A["E3a"]["sample_mean"]["zoh_dt_change_m8"])
    macros["EthreeSumChange"] = sci(A["E3a"]["sample_sum"]["zoh_dt_change_m8"])
    macros["EthreeTrapzChange"] = sci(A["E3a"]["time_trapz"]["zoh_dt_change_m8"])
    macros["EthreeRiemannChange"] = sci(A["E3a"]["time_riemann"]["zoh_dt_change_m8"])
    macros["EthreeExactChange"] = sci(A["E3a"]["time_exact"]["zoh_dt_change_m8"])
    macros["EthreeMeanErrOne"] = sci(A["E3b"]["sample_mean"]["zoh_dt_err_m1"])
    macros["EthreeMeanErrEight"] = sci(A["E3b"]["sample_mean"]["zoh_dt_err_m8"])
    macros["EthreeExactErrEight"] = sci(A["E3b"]["time_exact"]["zoh_dt_err_m8"])
    macros["EthreeRMEslope"] = f"{rme:.3f}"
    macros["EthreeRMEneg"] = str(neg)

    # ------------------------------------------------------------------ fix interaction
    _, fac = factorial(e3)
    A["factorial"] = fac
    labels = [
        r"none ($\Delta{=}\tau g$, Euler-$B$, sample mean)",
        r"time readout only (trapezoidal)",
        r"exact ZOH $B$ only",
        r"$\Delta{=}dt\,g$ only",
        r"$\Delta{=}dt\,g$ + trapezoidal",
        r"$\Delta{=}dt\,g$ + exact ZOH (sample mean)",
        r"$\Delta{=}dt\,g$ + exact ZOH + trapezoidal",
        r"$\Delta{=}dt\,g$ + exact ZOH + exact integral",
    ]
    rows = [f"{lab} & {cell(f['median_change_m8'])} \\\\" for lab, f in zip(labels, fac)]
    write("tab_interaction.tex", r"""\begin{table}[t]
\caption{One fix at a time (FR-E3-READOUT, split of the first half, $m{=}8$; median scale-normalized readout change over 32 units). The effects are not additive,
so no per-fix share is reported.}
\label{tab:interaction}
\centering\small
\begin{tabular}{lc}
\toprule
fixes applied & change \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
""")
    for i, key in enumerate(["FacNone", "FacTime", "FacZoh", "FacDt", "FacDtTime", "FacDtZoh", "FacDtZohTime", "FacAll"]):
        macros[key] = sci(fac[i]["median_change_m8"])

    # ------------------------------------------------------------------ FR-E2 exact decomposition (EXPLORATORY)
    e2 = [r for r in load("FR-E2-NEWOBS__uniform-real") if r["kind"] == "variant"]
    ybase = {(r["seed"], r["variant"], r["m"]): r["y_base"] for r in e2}
    art_zoh = mx([r for r in e2 if r["variant"] == "zoh_dt"], "artifact")
    seeds = sorted({r["seed"] for r in e2})
    rows = []
    A["E2"] = {"zoh_dt_max_artifact_vs_rk4": art_zoh, "decomposition": {}}
    for v in ORDER:
        for m in (2, 8):
            sp = sa = sc = st = 0.0
            cross_frac = []
            for s in seeds:
                P = [x - y for x, y in zip(ybase[(s, "zoh_dt", m)], ybase[(s, "zoh_dt", 1)])]
                Tt = [x - y for x, y in zip(ybase[(s, v, m)], ybase[(s, v, 1)])]
                R = [t - p for t, p in zip(Tt, P)]
                pp = sum(x * x for x in P)
                rr = sum(x * x for x in R)
                pr = sum(x * y for x, y in zip(P, R))
                tt = sum(x * x for x in Tt)
                sp, sa, sc, st = sp + pp, sa + rr, sc + 2 * pr, st + tt
                if tt > 0:
                    cross_frac.append(2 * pr / tt)
            tot_med = med([r for r in e2 if r["variant"] == v and r["m"] == m], "total_change")
            d = {"pooled_path_frac": sp / st, "pooled_artifact_frac": sa / st, "pooled_cross_frac": sc / st,
                 "cross_frac_min": min(cross_frac), "cross_frac_max": max(cross_frac), "median_total_change": tot_med}
            A["E2"]["decomposition"][f"{v}@{m}"] = d
            if v == "zoh_dt":
                rows.append(f"{VARIANT_TEX[v]} & ${m}$ & {cell(tot_med)} & \\multicolumn{{4}}{{c}}{{artifact $\\le{sci(art_zoh)}$ vs.\\ RK4 (proxy reference)}} \\\\")
            else:
                rows.append(f"{VARIANT_TEX[v]} & ${m}$ & {cell(tot_med)} & ${d['pooled_path_frac']:.3f}$ & ${d['pooled_artifact_frac']:.3f}$ & "
                            f"${d['pooled_cross_frac']:+.3f}$ & $[{d['cross_frac_min']:+.2f},{d['cross_frac_max']:+.2f}]$ \\\\")
    write("tab_newobs.tex", r"""\begin{table}[t]
\caption{Adding new observations of the same signal (FR-E2-NEWOBS; toy, 32 units). The change $T=y_m-y_1$ at base times splits \emph{exactly} as $T=P+R$, where $P$ is the change of the continuous-time solution on the new held path
(the change in the held-input reconstruction; no task or Bayesian information gain is implied) and $R$ is the change of the discretization artifact. Hence $\|T\|^2=\|P\|^2+\|R\|^2+2\langle P,R\rangle$; we report these three terms as fractions of $\sum_{\text{units}}\|T\|^2$ (they sum to 1)
and the per-unit range of the cross fraction. $P$ uses the exact-ZOH output as a proxy for the continuous-time held-path solution (validated against RK4 to the bound shown).
Median total change is relative to $\|y_1\|$. EXPLORATORY re-aggregation; the cross term shows that no per-unit ``share'' is well defined, and none of these fractions is a causal contribution.}
\label{tab:newobs}
\centering\small
\begin{tabular}{lcccccc}
\toprule
variant & $m$ & median $\|T\|/\|y_1\|$ & $\|P\|^2$ & $\|R\|^2$ & $2\langle P,R\rangle$ & cross range \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
""")
    macros["EtwoZohArt"] = sci(art_zoh)
    decs = [d for k, d in A["E2"]["decomposition"].items() if not k.startswith("zoh_dt@")]
    macros["EtwoCrossMin"] = f"{min(d['cross_frac_min'] for d in decs):+.2f}"
    macros["EtwoCrossMax"] = f"{max(d['cross_frac_max'] for d in decs):+.2f}"
    dn = A["E2"]["decomposition"]["zoh_nodt@8"]
    macros["EtwoNodtArtFrac"] = f"{dn['pooled_artifact_frac']:.2f}"
    macros["EtwoNodtCrossFrac"] = f"{dn['pooled_cross_frac']:+.2f}"
    de = A["E2"]["decomposition"]["eulerB_dt@8"]
    macros["EtwoEulerArtFrac"] = f"{de['pooled_artifact_frac']:.2f}"
    macros["EtwoEulerCrossFrac"] = f"{de['pooled_cross_frac']:+.2f}"
    e2ref = [r for r in load("FR-E2-NEWOBS__uniform-real") if r["kind"] == "reference"]
    macros["EtwoHoldErrOne"] = sci(med([r for r in e2ref if r["m"] == 1], "ct_held_err_to_truth"))
    macros["EtwoHoldErrEight"] = sci(med([r for r in e2ref if r["m"] == 8], "ct_held_err_to_truth"))
    macros["EtwoSlope"] = f"{median(per_seed_slopes([r for r in e2 if r['variant'] == 'zoh_dt'], 'err_to_truth', MS)):.2f}"

    # ------------------------------------------------------------------ P1-COMP-01 coupling
    comp = load("P1-COMP-01")
    rows = []
    A["COMP01"] = {}
    for case, lab in (("distinct", r"$a{=}1,\;c{=}0.5$"), ("equal", r"$a{=}c{=}1$")):
        rc = [r for r in comp if r["case"] == case]
        err = {r["m"]: r["layerwise_error"] for r in rc}
        chg = {r["m"]: r["layerwise_change"] for r in rc}
        inv = max(r["coupled_invariance"] for r in rc if r["m"] > 1)
        rk = max(r["coupled_vs_rk4"] for r in rc)
        sl = loglog_slope(MS, [err[m] for m in MS])
        A["COMP01"][case] = {"layerwise_error": err, "layerwise_change": chg, "coupled_invariance_max": inv,
                             "coupled_vs_rk4_max": rk, "slope": sl}
        rows.append(f"{lab} & " + " & ".join(cell(err[m]) for m in MS) + f" & ${sl:.2f}$ & {cell(chg[8])} & {cell(inv)} \\\\")
    write("tab_coupling.tex", r"""\begin{table}[t]
\caption{Two-layer linear cascade $\dot h_1=-ah_1+bu$, $\dot h_2=-ch_2+dh_1$ under interval splitting (P1-COMP-01; $b{=}d{=}1$; held input of FIRST\_RUN unit 0).
Columns $m$: error of the layerwise computation (layer 2 holds the layer-1 endpoint value) against the exact coupled solution, $\|h_2^{\mathrm{lw}}-h_2\|/\|h_2\|$ over base times.
``change'' is the layerwise change $m{=}8$ vs.\ $m{=}1$; the last column is the largest change of the exact coupled solution over $m$. No external observation is added in this experiment.}
\label{tab:coupling}
\centering\small
\begin{tabular}{lccccccc}
\toprule
case & $m{=}1$ & $m{=}2$ & $m{=}4$ & $m{=}8$ & slope & change & exact inv. \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
""")
    macros["CompErrOne"] = sci(A["COMP01"]["distinct"]["layerwise_error"][1])
    macros["CompErrEight"] = sci(A["COMP01"]["distinct"]["layerwise_error"][8])
    macros["CompSlope"] = f"{A['COMP01']['distinct']['slope']:.2f}"
    macros["CompSlopeEq"] = f"{A['COMP01']['equal']['slope']:.2f}"
    macros["CompInv"] = sci(max(A["COMP01"][c]["coupled_invariance_max"] for c in A["COMP01"]))
    macros["CompRK"] = sci(max(A["COMP01"][c]["coupled_vs_rk4_max"] for c in A["COMP01"]))

    # ------------------------------------------------------------------ numerics floor (appendix)
    n1 = [r for r in e4 if r["case"] == "N1_cancellation"]
    n1b = [r for r in e4 if r["case"] == "N1b_split_drift_fp64"]
    n4 = [r for r in e4 if r["case"] == "N4_split_drift_fp32_emulated"]
    rows1 = [f"{cell(r['z'], 1)} & {cell(r['rel_err_naive'])} & {cell(r['rel_err_expm1'])} \\\\" for r in n1]
    ms4 = sorted({r["m"] for r in n4})
    rows4 = []
    for m in ms4:
        f64 = {r["formula"]: r["rel_err_h1"] for r in n1b if r["m"] == m}
        f32 = {r["formula"]: r["rel_err_h1"] for r in n4 if r["m"] == m}
        rows4.append(f"${m}$ & {cell(f64.get('expm1'))} & {cell(f32.get('expm1'))} & {cell(f32.get('naive'))} \\\\")
    A["N1"] = n1
    A["N4"] = {m: {r["formula"]: r["rel_err_h1"] for r in n4 if r["m"] == m} for m in ms4}
    write("tab_numerics.tex", r"""\begin{table}[h]
\caption{Numerical floor (FR-E4). Left: relative error of the ZOH input coefficient $(e^{z}-1)/\lambda$ against a 50-digit reference. Right: splitting $[0,1]$ into $m$ held sub-steps
($\lambda{=}-1$, $g{=}\ln2$, exact $h(1)=0.5$); float32 is an \emph{emulation} (every primitive rounded, correctly rounded $\exp$), not a GPU kernel.}
\label{tab:numerics}
\centering\small
\begin{tabular}{rcc}
\toprule
$z$ & naive & \texttt{expm1} \\
\midrule
""" + "\n".join(rows1) + r"""
\bottomrule
\end{tabular}\hspace{1em}
\begin{tabular}{rccc}
\toprule
$m$ & fp64 \texttt{expm1} & fp32 \texttt{expm1} & fp32 naive \\
\midrule
""" + "\n".join(rows4) + r"""
\bottomrule
\end{tabular}
\end{table}
""")
    macros["NfourFloor"] = sci(A["N4"][16384]["expm1"])
    macros["NoneNaive"] = sci(next(r["rel_err_naive"] for r in n1 if abs(r["z"] + 1e-14) < 1e-20))

    # ------------------------------------------------------------------ hypothesis verdicts (appendix; not a results table)
    hyp = json.load(open(os.path.join(ROOT, "results", "raw", "hypotheses.json")))
    chyp = json.load(open(os.path.join(ROOT, "results", "raw", "P1-COMP-01__hypotheses.json")))
    def verdict(h):
        return "PASS (weak; see text)" if h["id"] == "H7c_restated" and h["status"] == "PASS" else h["status"]

    rows = [f"FIRST\\_RUN & {h['id'].replace('_', chr(92) + '_')} & {verdict(h)} \\\\" for h in hyp["hypotheses"]]
    rows += [f"P1-COMP-01 & {h['id']} ({h['case']}) & {h['status']} \\\\" for h in chyp["hypotheses"]]
    A["hypotheses"] = {"FIRST_RUN": {h["id"]: h["status"] for h in hyp["hypotheses"]},
                       "P1-COMP-01": {f"{h['id']}:{h['case']}": h["status"] for h in chyp["hypotheses"]}}
    write("tab_hypotheses.tex", r"""\begin{table}[h]
\caption{Pre-registered check verdicts, including the failed H7c\_original (mis-specified before the run; amendment A2) and the weakly supported H7c\_restated. These are bookkeeping, not scientific results.}
\label{tab:hypotheses}
\centering\small
\begin{tabular}{llc}
\toprule
run & check & verdict \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
""")

    # ------------------------------------------------------------------ figure (pgfplots): convergence
    # Palette slots 1-3 of the dataviz reference palette (validated, light mode);
    # every series also has a distinct marker and dash pattern (not color alone).
    def coords(series):
        return " ".join(f"({m},{y:.6e})" for m, y in series if y and y > 0)

    s_eu = [(m, A["E1"]["eulerB_dt"]["median_artifact"][m]) for m in MS]
    s_bi = [(m, A["E1"]["bilinear_dt"]["median_artifact"][m]) for m in MS]
    s_nd = [(m, A["E1"]["zoh_nodt"]["median_artifact"][m]) for m in MS]
    s_cd = [(m, A["COMP01"]["distinct"]["layerwise_error"][m]) for m in MS]
    s_ce = [(m, A["COMP01"]["equal"]["layerwise_error"][m]) for m in MS]
    write("fig_convergence.tex", r"""\begin{figure}[t]
\centering
\definecolor{seriesA}{HTML}{2A78D6}\definecolor{seriesB}{HTML}{EB6834}\definecolor{seriesC}{HTML}{1BAF7A}
\begin{tikzpicture}
\begin{groupplot}[group style={group size=2 by 1, horizontal sep=0.85cm},
  width=0.47\columnwidth, height=0.47\columnwidth, xmode=log, ymode=log, log basis x=2,
  xtick={1,2,4,8}, xticklabels={1,2,4,8}, xlabel={sub-steps $m$}, tick label style={font=\footnotesize},
  label style={font=\footnotesize}, title style={font=\footnotesize}, grid=major, grid style={gray!20, line width=0.3pt},
  axis line style={gray!60}, legend style={font=\scriptsize, draw=none, fill=none}, legend cell align=left]
\nextgroupplot[title={(a) single layer}, ylabel={relative error}, ymin=5e-5, ymax=5,
  legend style={at={(0.5,-0.33)}, anchor=north}]
\addplot[seriesA, line width=1pt, mark=*, mark size=1.6pt] coordinates {""" + coords(s_eu) + r"""};
\addlegendentry{Euler-$B$, $\Delta{=}dt\,g$}
\addplot[seriesB, line width=1pt, dashed, mark=square*, mark size=1.6pt] coordinates {""" + coords(s_bi) + r"""};
\addlegendentry{bilinear, $\Delta{=}dt\,g$}
\addplot[seriesC, line width=1pt, dotted, mark=triangle*, mark size=2pt] coordinates {""" + coords(s_nd) + r"""};
\addlegendentry{exact ZOH, $\Delta{=}\tau g$}
\nextgroupplot[title={(b) two-layer cascade}, ymin=5e-3, ymax=0.5,
  legend style={at={(0.5,-0.33)}, anchor=north}]
\addplot[seriesA, line width=1pt, mark=*, mark size=1.6pt] coordinates {""" + coords(s_cd) + r"""};
\addlegendentry{$a{=}1,\,c{=}0.5$}
\addplot[seriesB, line width=1pt, dashed, mark=square*, mark size=1.6pt] coordinates {""" + coords(s_ce) + r"""};
\addlegendentry{$a{=}c{=}1$}
\end{groupplot}
\end{tikzpicture}
\caption{Error against the exact held-path solution as the same held interval is split into $m$ sub-steps: (a) single layer (FR-E1-SPLIT; medians over 32 toy units); (b) two-layer cascade (P1-COMP-01; one deterministic case per line).
Exact ZOH with $\Delta{=}dt\,g$ (a) and the exact coupled solution (b) stay at $10^{-15}$ and are not drawn. The $\Delta{=}\tau g$ line starts at $m{=}2$ because it is exact at $m{=}1$ by construction.
Values are listed in \cref{tab:split,tab:coupling}.}
\label{fig:convergence}
\end{figure}
""")

    # ------------------------------------------------------------------ hypothesis evidence used in the text
    hv = {h["id"]: h for h in hyp["hypotheses"]}
    macros["HsevenOrigSlope"] = f"{hv['H7c_original']['evidence']['median_slope_change_time_riemann_m2_m8']:+.2f}"
    macros["HfourEulerFrac"] = f"{round(hv['H4']['evidence']['eulerB_nodt']['frac_nondecreasing_m2_to_m8'] * 32)}"
    macros["NunitsPrimary"] = str(len(seeds))
    fr_man = json.load(open(os.path.join(ROOT, "run_manifest.json")))
    macros["FirstRunSeconds"] = f"{fr_man['wall_clock_seconds']:.1f}"
    macros["CompSeconds"] = f"{fr_man['subsequent_runs'][0]['wall_clock_seconds']:.2f}"

    # ------------------------------------------------------------------ P1-REAL-01 (trained official TIDES; seed-0 pilot)
    rdir = os.path.join(ROOT, "results", "raw")
    summ = json.load(open(os.path.join(rdir, "P1-REAL-01__summary.json")))
    trn = json.load(open(os.path.join(rdir, "P1-REAL-01__train.json")))
    lay = json.load(open(os.path.join(rdir, "P1-REAL-01__layer_diagnostic.json")))
    conv = json.load(open(os.path.join(rdir, "P1-REAL-01__convention_check.json")))
    adap = json.load(open(os.path.join(rdir, "P1-REAL-01__adapter_check.json")))
    C = summ["conditions"]
    A["REAL"] = {"summary": summ, "train": {k: trn[k] for k in ("selected_step", "selected_dev_mse", "y_stats",
                                                               "train_loop_seconds", "total_seconds")}}

    def ci(c):
        return f"$[{sci(c[0])},\,{sci(c[1])}]$"

    short = {
        "NO PRACTICAL DIFFERENCE (CI inside +-5% margin)": r"within $\pm5\%$",
        "NATIVE BETTER (CI < 0); not shown beyond margin": r"lower",
        "NATIVE BETTER (CI < 0)": r"lower, beyond margin",
        "NATIVE WORSE (CI > 0); not shown beyond margin": r"higher",
        "NATIVE WORSE (CI > 0)": r"higher, beyond margin",
        "INCONCLUSIVE (CI includes 0 and exceeds the margin)": "inconclusive",
    }
    rows = []
    def e4(x):
        v = 1e4 * x
        if v == 0:
            return "0"
        return f"{v:+.0f}" if abs(v) >= 100 else f"{v:+.1f}"

    for n, lab in (("C0", "C0"), ("S2", "S2"), ("S4", "S4"), ("S8", "S8"), ("H8", "H8"), ("J1", "J1$^\\dagger$")):
        c = C[n]
        verdict = "identical inputs (check)" if n == "C0" else short[c["equivalence_verdict"]]
        rows.append(f"{lab} & {cell(c['disc_native_mean'])} & {cell(c['disc_resampled_mean'])} & {cell(c['mse_native_mean'], 3)} & "
                    f"{cell(c['mse_resampled_mean'], 3)} & ${e4(c['paired_diff_mean'])}$ $[{e4(c['paired_diff_ci'][0])},\\,{e4(c['paired_diff_ci'][1])}]$ & {verdict} \\\\")
    write("tab_real.tex", r"""\begin{table}[t]
\caption{DEVELOPMENT run (P1-REAL-01): trained official TIDES, seed 0, on its own test set (256 trajectories, ids 640--895; one checkpoint selected on the calibration split; paired).
``disc.'': mean relative $\ell_2$ change of the per-step outputs at the 32 training-grid times against the same arm on C0.
MSE: per-trajectory mean squared error to the teacher at those times (original units; label s.d.\ """ + f"{trn['y_stats'][1]:.2f}" + r""").
$\Delta$MSE: mean paired difference native $-$ resampled in units of $10^{-4}$ (label units squared) with a 95\% bootstrap CI; the margin is $\pm5\%$ of the point-estimated resampled mean MSE of the same condition (exploratory rule of the development run).
Verdict (native vs.\ resampled MSE): lower/higher if the CI excludes 0 on that side. Runtimes of this run are not tabulated; they were forward-only and are superseded by \cref{tab:timing}.
C0 is the training grid; S$m$ and H8 (first half split by 8) keep the held path; $^\dagger$J1 (random observation times) is a secondary non-refinement condition whose held path differs by construction.}
\label{tab:real}
\centering\small
\begin{tabular}{lcccccc}
\toprule
cond. & disc.\ native & disc.\ resampled & MSE native & MSE resampled & $\Delta$MSE [95\% CI] ($10^{-4}$) & margin rule \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
""")
    rows = []
    for n in ("C0", "S8", "H8", "J1"):
        c = C[n]
        rows.append(f"{n} & {cell(c['pool_native_mean_abs_err_mean'])} & {cell(c['pool_native_time_abs_err_mean'])} & "
                    f"{cell(c['pool_resampled_mean_abs_err_mean'])} & {cell(c['pool_native_mean_abs_change_mean'])} & "
                    f"{cell(c['pool_native_time_abs_change_mean'])} & {cell(c['pool_resampled_mean_abs_change_mean'])} \\\\")
    pl = [json.loads(l)["pooled_label"] for l in open(os.path.join(rdir, "P1-REAL-01.jsonl")) if '"condition": "C0"' in l]
    pl_abs = sum(abs(x) for x in pl) / len(pl)
    write("tab_pool.tex", r"""\begin{table}[t]
\caption{Pooled readout of the development checkpoint on its own test set (P1-REAL-01), label units, means over 256 test trajectories. Left: $n^{-1}\sum_i|p_i(c)-\bar y_i|$; right: $n^{-1}\sum_i|p_i(c)-p_i(\mathrm{C0})|$, with $p=p^{\mathrm{mean}}$ (``native mean'', token mean as in the TIDES classifier head), $p=p^{\mathrm{time}}$ (``native time'', right-endpoint time-weighted sum of the same native outputs; a pooling-only ablation, not an exact integral) or $p=p^{\mathrm{res}}$ (``resampled'', token mean of the 32 resampled outputs); definitions in \cref{sec:real}. Pooled label $\bar y_i$: time average of the teacher output over $[0,T]$ by Simpson's rule on its RK4 nodes (mean absolute value """ + f"{pl_abs:.2f}" + r""").}
\label{tab:pool}
\centering\small
\begin{tabular}{lcccccc}
\toprule
 & \multicolumn{3}{c}{error to pooled label} & \multicolumn{3}{c}{change vs.\ C0} \\
\cmidrule(lr){2-4}\cmidrule(lr){5-7}
cond. & native mean & native time & resampled & native mean & native time & resampled \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
""")
    rows = []
    for n in ("S2", "S4", "S8", "H8"):
        d = lay["conditions"][n]
        rows.append(f"{n} & " + " & ".join(cell(d[dt][k]["mean"]) for k in ("block1", "block2", "output") for dt in ("float32", "float64")) + " \\\\")
    write("tab_layers.tex", r"""\begin{table}[t]
\caption{Where the splitting change appears in the development checkpoint (EXPLORATORY, added after its results were seen). Mean relative $\ell_2$ change against C0 at the training-grid times of the
features after each block and of the (normalized) output, with the frozen weights evaluated in float32 and cast to float64. The encoder output is unchanged (0) in all cases.}
\label{tab:layers}
\centering\small
\begin{tabular}{lcccccc}
\toprule
 & \multicolumn{2}{c}{block 1} & \multicolumn{2}{c}{block 2} & \multicolumn{2}{c}{output} \\
\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}
cond. & fp32 & fp64 & fp32 & fp64 & fp32 & fp64 \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
""")
    macros["RealStep"] = str(trn["selected_step"])
    macros["RealDevMSE"] = sci(trn["selected_dev_mse"])
    macros["RealTrainSec"] = f"{trn['total_seconds']:.0f}"
    macros["RealLabelSD"] = f"{trn['y_stats'][1]:.2f}"
    macros["RealDiscSeight"] = sci(C["S8"]["disc_native_mean"])
    macros["RealDiscStwo"] = sci(C["S2"]["disc_native_mean"])
    macros["RealDiscSeightCIlo"] = sci(C["S8"]["disc_native_ci"][0])
    macros["RealDiscSeightCIhi"] = sci(C["S8"]["disc_native_ci"][1])
    macros["RealMSEczero"] = sci3(C["C0"]["mse_native_mean"])
    macros["RealMSEseight"] = sci3(C["S8"]["mse_native_mean"])
    macros["RealMSEheight"] = sci3(C["H8"]["mse_native_mean"])
    for n in ("S2", "S8", "H8"):
        c = C[n]
        macros[f"RealRelDiff{n.replace('2', 'two').replace('8', 'eight')}"] = f"{100 * c['paired_diff_mean'] / c['mse_resampled_mean']:+.1f}"
    macros["RealRunNatSeight"] = f"{C['S8']['runtime_native']['seconds_batch']:.2f}"
    macros["RealRunResSeight"] = f"{C['S8']['runtime_resampled']['seconds_batch']:.3f}"
    macros["RealRunNatCzero"] = f"{C['C0']['runtime_native']['seconds_batch']:.3f}"
    macros["RealPoolMeanHeight"] = sci(C["H8"]["pool_native_mean_abs_err_mean"])
    macros["RealPoolTimeHeight"] = sci(C["H8"]["pool_native_time_abs_err_mean"])
    macros["RealPoolResHeight"] = sci(C["H8"]["pool_resampled_mean_abs_err_mean"])
    macros["RealPoolCzero"] = sci(C["C0"]["pool_native_mean_abs_err_mean"])
    macros["RealPoolLabelAbs"] = f"{pl_abs:.2f}"
    macros["RealLayerOneFp"] = sci(max(lay["conditions"][n]["float32"]["block1"]["mean"] for n in ("S2", "S4", "S8", "H8")))
    macros["RealLayerOneDp"] = sci(max(lay["conditions"][n]["float64"]["block1"]["mean"] for n in ("S2", "S4", "S8", "H8")))
    macros["RealLayerTwoMin"] = sci(min(lay["conditions"][n]["float64"]["block2"]["mean"] for n in ("S2", "S4", "S8", "H8")))
    macros["RealLayerTwoMax"] = sci(max(lay["conditions"][n]["float64"]["block2"]["mean"] for n in ("S2", "S4", "S8", "H8")))
    macros["RealJoneMSE"] = sci(C["J1"]["mse_native_mean"])
    macros["RealEvalSec"] = f"{summ['eval_seconds']:.0f}"
    macros["ConvCodeRight"] = sci(max(conv[g]["max_abs_code_minus_right"] for g in ("irregular", "uniform")))
    macros["ConvShiftUniform"] = sci(conv["uniform"]["max_abs_code_state_k_minus_paper_state_k_plus_1"])
    macros["ConvShiftIrregular"] = sci(conv["irregular"]["max_abs_code_state_k_minus_paper_state_k_plus_1"])
    macros["AdapterStep"] = f"{adap['train_seconds_per_step_batch32']:.3f}"
    macros["AdapterParams"] = f"{adap['n_parameters']:,}".replace(",", "{,}")
    dev_curve = [c["dev_mse"] for c in trn["curve"] if c["step"] > 0]
    macros["RealDevMax"] = sci(max(dev_curve))
    A["REAL"]["layer"] = lay
    A["REAL"]["convention"] = {k: v for k, v in conv.items() if k != "status"}

    # ------------------------------------------------------------------ P1-REAL-02 (seed repetition)
    d2 = os.path.join(rdir, "P1-REAL-02")
    order = [("dev_seed0", r"0$^\ddagger$"), ("seed1", "1"), ("seed2", "2"), ("seed3", "3"), ("seed4", "4")]
    R2 = {k: json.load(open(os.path.join(d2, k, "eval_summary.json"))) for k, _ in order}
    agg2 = json.load(open(os.path.join(d2, "aggregate.json")))
    eq2 = json.load(open(os.path.join(d2, "eqcheck.json")))
    dh2 = json.load(open(os.path.join(d2, "data_hash.json")))
    th2 = json.load(open(os.path.join(d2, "testset_hash.json")))
    tr2 = {k: json.load(open(os.path.join(d2, k, "train.json"))) for k in ("seed1", "seed2", "seed3", "seed4")}
    A["REAL2"] = {"aggregate": {k: v for k, v in agg2.items() if k != "development_row_seed0_new_testset"}, "eqcheck": eq2}
    HD = json.load(open(os.path.join(d2, "h8_decomposition", "summary.json")))["rows"]
    A["REAL2"]["h8_decomposition"] = HD
    seeds_order = [("seed1", "1"), ("seed2", "2"), ("seed3", "3"), ("seed4", "4")]

    def sgn(x, nd=3):
        return f"${x:+.{nd}f}$"

    def fci(c, fmt="{:.3f}"):
        return "$[" + fmt.format(c[0]) + ",\\," + fmt.format(c[1]) + "]$"

    # float32 vs float64 S8 discrepancy (stored per-trajectory values, Python floats)
    fp = {}
    for k, _ in seeds_order:
        recs8 = [json.loads(l) for l in open(os.path.join(d2, k, "eval.jsonl")) if '"condition": "S8"' in l]
        e32, e64 = R2[k]["S8_disc_float32"]["estimate"], R2[k]["S8_disc_float64"]["estimate"]
        fp[k] = {"est_diff": abs(e32 - e64), "rel": abs(e32 - e64) / e32,
                 "traj_max": max(abs(r["disc_native"] - r["disc_native_float64"]) for r in recs8),
                 "traj_min_disc": min(r["disc_native"] for r in recs8)}
    A["REAL2"]["fp32_vs_fp64"] = fp

    rows = []
    for k, lab in seeds_order:
        d = R2[k]
        e = d["S8_disc_float32"]
        rows.append(f"{lab} & {d['selected_step']} & ${d['selected_dev_mse']:.4f}$ & ${e['estimate']:.4f}$ {fci(e['ci95'], '{:.4f}')} \\\\")
    write("tab_seeds_coupling.tex", r"""\begin{table}[t]
\caption{Model-coupling effect (P1-REAL-02, training seeds 1--4; same task, data and checkpoint rule; shared test set of 256 trajectories, ids 10000--10255).
Step and calib.\ MSE: selected checkpoint and its calibration MSE (label units squared).
S8 disc.: mean over trajectories of the relative $\ell_2$ change of the final per-step outputs at the 32 training-grid times when every held interval is split into 8 sub-steps, against C0 (float32).
Brackets: 95\% paired bootstrap CI over test trajectories with the seed fixed.}
\label{tab:seeds-coupling}
\centering\small
\begin{tabular}{rccc}
\toprule
seed & step & calib.\ MSE & S8 disc.\ [95\% CI] \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
""")
    rows = []
    for k, lab in seeds_order:
        d, h = R2[k], HD[k]
        rows.append(f"{lab} & ${d['primary_D']['estimate']:.3f}$ {fci(d['primary_D']['ci95'])} & {sgn(h['pmean_minus_pC0']['mean'])} & "
                    f"{sgn(h['W']['mean'])} & {sgn(h['M']['mean'])} {fci(h['M']['ci95'], '{:+.3f}')} & "
                    f"{sgn(h['Q']['mean'])} {fci(h['Q']['ci95'], '{:+.3f}')} & ${h['Q']['mean_abs']:.3f}$ \\\\")
    write("tab_seeds_readout.tex", r"""\begin{table*}[t]
\caption{Readout decomposition under the same-path density change H8 (first half of $[0,T]$ split by 8; 144 tokens), training seeds 1--4, label units, means over the 256 test trajectories.
$D_s$ (primary, chosen after the development run): mean of $|p^{\mathrm{mean}}(\mathrm{H8})-p(\mathrm{C0})|-|p^{\mathrm{time}}(\mathrm{H8})-p(\mathrm{C0})|$.
Per trajectory, exactly, $p^{\mathrm{mean}}(\mathrm{H8})-p(\mathrm{C0})=W+M$ and $p^{\mathrm{time}}(\mathrm{H8})-p(\mathrm{C0})=Q$ with $W=\sum_j(a_j-w_j)b_j=\tfrac{7}{18}(A-B)$, $M=\sum_ja_j(z_j-b_j)$, $Q=\sum_jw_j(z_j-b_j)$; $b_j$ is the C0 output of token $j$'s base interval, $z_j$ the native H8 output, $a_j=1/144$, $w_j=dt_j/T$, and $A$, $B$ are the mean C0 outputs over the first and second half of $[0,T]$.
$W$ uses only C0 outputs: it is the same for any model whose H8 outputs repeat the C0 output within each base interval.
The signed terms are not an additive decomposition of the absolute-value estimand $D_s$.
Brackets: 95\% paired bootstrap CI (seed fixed).}
\label{tab:seeds-readout}
\centering\small
\begin{tabular}{rcccccc}
\toprule
seed & $D_s$ [95\% CI] & $p^{\mathrm{mean}}-p(\mathrm{C0})$ & $W$ & $M$ [95\% CI] & $Q$ [95\% CI] & $|Q|$ \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table*}
""")
    vsym = {"no practical difference (CI inside +-5%)": "$=$", "native lower; CI not beyond margin": "$<$",
            "native lower, beyond margin": r"$\ll$", "native higher; CI not beyond margin": "$>$",
            "native higher, beyond margin": r"$\gg$", "inconclusive": "?", "NA (denominator too small)": "NA"}

    def pct(x):
        return f"{100 * x:+.1f}"

    def rc(L):
        return f"${pct(L['r'])}$ $[{pct(L['r_ci95'][0])},\\,{pct(L['r_ci95'][1])}]$ & {vsym[L['verdict']]}"

    rows = [f"{lab} & " + " & ".join(rc(R2[k]["loss"][c]) for c in ("S2", "S8", "H8", "J1")) + " \\\\" for k, lab in seeds_order]
    write("tab_seeds_loss.tex", r"""\begin{table*}[t]
\caption{Task-risk effect: loss contrast $r_s=(\overline{L}_{\mathrm{native}}-\overline{L}_{\mathrm{resampled}})/\overline{L}_{\mathrm{resampled}}$ in percent (per-trajectory MSE at the 32 training-grid times; numerator and denominator recomputed in every bootstrap draw), training seeds 1--4.
Verdict: $=$ CI inside $\pm5\%$; $<$ / $>$ native lower / higher (CI excludes 0); $\ll$ / $\gg$ also beyond the margin; ? inconclusive. The $\pm5\%$ margin is a convention.
S2, S8 and H8 keep the held path; J1 (random observation times) changes the observed path. Timing: \cref{tab:timing}.}
\label{tab:seeds-loss}
\centering\small
\begin{tabular}{rcccccccc}
\toprule
seed & \multicolumn{2}{c}{$r_s$(S2) [95\% CI]} & \multicolumn{2}{c}{$r_s$(S8) [95\% CI]} & \multicolumn{2}{c}{$r_s$(H8) [95\% CI]} & \multicolumn{2}{c}{$r_s$(J1) [95\% CI]} \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table*}
""")
    d, h = R2["dev_seed0"], HD["dev_seed0"]
    L = d["loss"]
    items = [("selected step / calibration MSE", f"{d['selected_step']} / ${d['selected_dev_mse']:.4f}$"),
             ("S8 disc.\\ [95\\% CI]", f"${d['S8_disc_float32']['estimate']:.4f}$ {fci(d['S8_disc_float32']['ci95'], '{:.4f}')}"),
             ("$D_s$ [95\\% CI]", f"${d['primary_D']['estimate']:.3f}$ {fci(d['primary_D']['ci95'])}"),
             ("$p^{\\mathrm{mean}}-p(\\mathrm{C0})$, $W$, $M$, $Q$ (means)",
              f"{sgn(h['pmean_minus_pC0']['mean'])}, {sgn(h['W']['mean'])}, {sgn(h['M']['mean'])}, {sgn(h['Q']['mean'])}")]
    for c in ("S2", "S8", "H8", "J1"):
        items.append((f"$r_s$({c}) [95\\% CI], verdict", rc(L[c]).replace(" & ", " ")))
    write("tab_dev_newtest.tex", r"""\begin{table}[h]
\caption{Development checkpoint (seed 0, P1-REAL-01) evaluated with the P1-REAL-02 protocol on the new shared test set; not part of the replication criterion. Definitions as in \cref{tab:seeds-coupling,tab:seeds-readout,tab:seeds-loss}.}
\label{tab:dev-newtest}
\centering\small
\begin{tabular}{ll}
\toprule
quantity & development checkpoint, new test set \\
\midrule
""" + "\n".join(f"{a} & {b} \\\\" for a, b in items) + r"""
\bottomrule
\end{tabular}
\end{table}
""")
    trows = []
    for k, lab in order:
        tm = R2[k]["timing"]
        for c in ("C0", "S8", "H8"):
            t_ = tm[c]
            trows.append(f"{lab} & {c} & {t_['tokens_native']} & ${t_['native_end_to_end']['median_wall_s']:.3f}$ & ${t_['native_forward_only']['median_wall_s']:.3f}$ & "
                         f"${t_['resampled_end_to_end']['median_wall_s']:.3f}$ & ${t_['resampled_forward_only']['median_wall_s']:.3f}$ & "
                         f"${t_['native_end_to_end']['median_cpu_s']:.2f}$ \\\\")
    write("tab_timing.tex", r"""\begin{table}[h]
\caption{P1-REAL-02 timing (one batch of 256 sequences; median of 5 timed calls after 2 warm-ups; \texttt{inference\_mode}; 2 threads). End-to-end includes tensor construction, LOCF resampling for the resampled arm, forward, de-normalization and readout mapping; forward-only is the model call on prebuilt tensors. CPU seconds are process CPU time summed over threads. Timed repeats are not independent samples. $^\ddagger$Development checkpoint (seed 0).}
\label{tab:timing}
\centering\small
\begin{tabular}{rcrccccc}
\toprule
seed & cond. & tokens & nat.\ e2e & nat.\ fwd & res.\ e2e & res.\ fwd & nat.\ e2e CPU \\
\midrule
""" + "\n".join(trows) + r"""
\bottomrule
\end{tabular}
\end{table}
""")
    seeds4 = ["seed1", "seed2", "seed3", "seed4"]
    Dv = [R2[k]["primary_D"]["estimate"] for k in seeds4]
    Dlo = [R2[k]["primary_D"]["ci95"][0] for k in seeds4]
    S8v = [R2[k]["S8_disc_float32"]["estimate"] for k in seeds4]
    rS8 = [R2[k]["loss"]["S8"]["r"] for k in seeds4]
    rH8 = [R2[k]["loss"]["H8"]["r"] for k in seeds4]
    rJ1 = [R2[k]["loss"]["J1"]["r"] for k in seeds4]
    ratio = [R2[k]["timing"]["S8"]["native_end_to_end"]["median_wall_s"] / R2[k]["timing"]["S8"]["resampled_end_to_end"]["median_wall_s"] for k in seeds4]
    fratio = [R2[k]["timing"]["S8"]["native_forward_only"]["median_wall_s"] / R2[k]["timing"]["S8"]["resampled_forward_only"]["median_wall_s"] for k in seeds4]
    macros["RtwoDmin"] = sci(min(Dv), 3)
    macros["RtwoDmax"] = sci(max(Dv), 3)
    macros["RtwoDlomin"] = sci(min(Dlo), 3)
    macros["RtwoSeightMin"] = sci(min(S8v))
    macros["RtwoSeightMax"] = sci(max(S8v))
    macros["RtwoRSeightMin"] = pct(min(rS8))
    macros["RtwoRSeightMax"] = pct(max(rS8))
    macros["RtwoRHeightMin"] = pct(min(rH8))
    macros["RtwoRHeightMax"] = pct(max(rH8))
    macros["RtwoRJoneMin"] = pct(min(rJ1))
    macros["RtwoRJoneMax"] = pct(max(rJ1))
    macros["RtwoRJonePilotOld"] = pct(agg2["seed0_pilot_old_testset_r_rederived"]["loss"]["J1"]["r"])
    macros["RtwoRJoneDev"] = pct(R2["dev_seed0"]["loss"]["J1"]["r"])
    macros["RtwoRatioMin"] = f"{min(ratio):.1f}"
    macros["RtwoRatioMax"] = f"{max(ratio):.1f}"
    macros["RtwoFratioMin"] = f"{min(fratio):.1f}"
    macros["RtwoFratioMax"] = f"{max(fratio):.1f}"
    macros["RtwoStepsMin"] = str(min(tr2[k]["selected_step"] for k in seeds4))
    macros["RtwoStepsMax"] = str(max(tr2[k]["selected_step"] for k in seeds4))
    macros["RtwoTrainWall"] = f"{sum(tr2[k]['total_wall_seconds'] for k in seeds4):.0f}"
    macros["RtwoTrainCPU"] = f"{sum(tr2[k]['train_loop_cpu_seconds'] for k in seeds4):.0f}"
    macros["RtwoEvalWall"] = f"{sum(R2[k]['eval_wall_seconds'] for k, _ in order):.0f}"
    macros["RtwoDataWall"] = f"{dh2['wall_seconds']:.0f}"
    macros["RtwoTestWall"] = f"{th2['wall_seconds']:.0f}"
    macros["RtwoPoolMeanMin"] = sci(min(R2[k]["pooled"]["H8"]["mean"] for k in seeds4))
    macros["RtwoPoolMeanMax"] = sci(max(R2[k]["pooled"]["H8"]["mean"] for k in seeds4))
    macros["RtwoPoolTimeMin"] = sci(min(R2[k]["pooled"]["H8"]["time"] for k in seeds4))
    macros["RtwoPoolTimeMax"] = sci(max(R2[k]["pooled"]["H8"]["time"] for k in seeds4))
    macros["RtwoPoolResMin"] = sci(min(R2[k]["pooled"]["H8"]["resampled"] for k in seeds4))
    macros["RtwoPoolResMax"] = sci(max(R2[k]["pooled"]["H8"]["resampled"] for k in seeds4))
    macros["RtwoSeightFold"] = f"{max(S8v) / min(S8v):.1f}"
    macros["RtwoCzeroRatioMax"] = f"{max(R2[k]['timing']['C0']['native_end_to_end']['median_wall_s'] / R2[k]['timing']['C0']['resampled_end_to_end']['median_wall_s'] for k in seeds4):.2f}"
    macros["RtwoCzeroRatioMin"] = f"{min(R2[k]['timing']['C0']['native_end_to_end']['median_wall_s'] / R2[k]['timing']['C0']['resampled_end_to_end']['median_wall_s'] for k in seeds4):.2f}"
    over = [R2[k]["timing"]["S8"]["resampled_end_to_end"]["median_wall_s"] - R2[k]["timing"]["S8"]["resampled_forward_only"]["median_wall_s"] for k in seeds4]
    macros["RtwoResOverMin"] = f"{min(over):.3f}"
    macros["RtwoResOverMax"] = f"{max(over):.3f}"
    # End-to-end and forward-only are separate timing jobs; count cells where the
    # end-to-end median is below the forward-only median (run-to-run variation).
    inv = []
    for k, _ in order:
        for cond, tv in R2[k]["timing"].items():
            for arm in ("native", "resampled"):
                e = tv[f"{arm}_end_to_end"]["median_wall_s"]
                f_ = tv[f"{arm}_forward_only"]["median_wall_s"]
                inv.append((e < f_, (f_ - e) / f_))
    macros["RtwoInvN"] = str(sum(1 for x, _ in inv if x))
    macros["RtwoInvTot"] = str(len(inv))
    macros["RtwoInvMaxPct"] = f"{100 * max((d for x, d in inv if x), default=0.0):.1f}"
    # float32 vs float64 (checkpoint-specific precision diagnostic)
    macros["RtwoFpEstMax"] = sci(max(fp[k]["est_diff"] for k in seeds4))
    macros["RtwoFpRelMax"] = sci(max(fp[k]["rel"] for k in seeds4))
    macros["RtwoFpTrajMax"] = sci(max(fp[k]["traj_max"] for k in seeds4))
    macros["RtwoDiscTrajMin"] = sci(min(fp[k]["traj_min_disc"] for k in seeds4))
    # H8 signed decomposition (one frozen forward per checkpoint; reproduces stored pooled values)
    def hr(key, field="mean", fmt="{:+.3f}"):
        v = [HD[k][key][field] for k in seeds4]
        return fmt.format(min(v)), fmt.format(max(v))
    for name, key, field, fmt in (("Delta", "pmean_minus_pC0", "mean", "{:+.2f}"), ("W", "W", "mean", "{:+.2f}"),
                                  ("M", "M", "mean", "{:+.3f}"), ("Mabs", "M", "mean_abs", "{:.3f}"),
                                  ("Mend", "M_end", "mean_abs", "{:.4f}"), ("Qabs", "Q", "mean_abs", "{:.3f}"),
                                  ("DeltaAbs", "pmean_minus_pC0", "mean_abs", "{:.2f}"), ("Wabs", "W", "mean_abs", "{:.2f}")):
        lo, hi = hr(key, field, fmt)
        macros[f"Dec{name}Min"], macros[f"Dec{name}Max"] = lo, hi
    ab = [HD[k]["A_minus_B_mean"] for k in seeds4]
    macros["DecABMin"], macros["DecABMax"] = f"{min(ab):.2f}", f"{max(ab):.2f}"
    macros["DecSignMin"] = f"{100 * min(HD[k]['frac_sign_W_eq_sign_change'] for k in seeds4):.0f}"
    rep = [HD[k]["pooled_error"]["replicated_baseline_token_mean"] for k in seeds4]
    macros["DecRepErrMin"], macros["DecRepErrMax"] = f"{min(rep):.2f}", f"{max(rep):.2f}"
    macros["DecMismatch"] = sci(max(HD[k]["max_abs_mismatch_vs_stored"] for k in HD)) if max(HD[k]["max_abs_mismatch_vs_stored"] for k in HD) else "0"
    macros["DecIdentity"] = sci(max(HD[k]["max_abs_identity_residual"] for k in HD))
    hsum = json.load(open(os.path.join(d2, "h8_decomposition", "summary.json")))
    macros["DecWall"] = f"{hsum['wall_seconds']:.1f}"
    macros["RtwoEqMax"] = sci(eq2["max_abs_tensor_diff"]) if eq2["max_abs_tensor_diff"] else "0"
    macros["RtwoEqEqual"] = r"\text{exactly equal}" if eq2["all_tensors_equal"] else r"\text{different}"

    # ------------------------------------------------------------------ P1-HAR-01 (real sensor windows; one checkpoint)
    hd = os.path.join(rdir, "P1-HAR-01")
    if os.path.exists(os.path.join(hd, "aggregate.json")):
        HA = json.load(open(os.path.join(hd, "aggregate.json")))
        HT = json.load(open(os.path.join(hd, "train.json")))
        HL = json.load(open(os.path.join(hd, "cost_ledger.json")))
        HS = json.load(open(os.path.join(hd, "smoke.json")))
        A["HAR"] = {"aggregate": {k: v for k, v in HA.items() if k not in ("timing",)}, "train": {k: HT[k] for k in HT if k != "curve"},
                    "ledger": HL, "smoke": {k: v for k, v in HS.items() if k != "rule"}}
        subs = HA["subjects"]

        def f3(x):
            return f"{x:+.3f}"

        def fci(c):
            return f"$[{c[0]:+.3f},\\,{c[1]:+.3f}]$"
        rows = []
        for s_ in subs:
            k = str(s_)
            rows.append(f"{s_} & {HA['windows_per_subject'][k]} & ${HA['ce']['C0/native_mean']['per_subject'][k]:.3f}$ & "
                        f"${HA['ce']['H8/native_mean']['per_subject'][k]:.3f}$ & ${HA['ce']['H8/native_time']['per_subject'][k]:.3f}$ & "
                        f"${HA['primary_D']['per_subject'][k]:+.3f}$ & ${HA['accuracy']['C0/native_mean']['per_subject'][k]:.3f}$ & "
                        f"${HA['accuracy']['H8/native_mean']['per_subject'][k]:.3f}$ & ${HA['accuracy']['H8/native_time']['per_subject'][k]:.3f}$ & "
                        f"${HA['flip_vs_C0']['H8/native_mean']['per_subject'][k]:.3f}$ \\\\")
        pd = HA["primary_D"]
        rows.append(r"\midrule")
        rows.append(f"mean & {HA['n_windows']} & ${HA['ce']['C0/native_mean']['mean_over_subjects']:.3f}$ & ${HA['ce']['H8/native_mean']['mean_over_subjects']:.3f}$ & "
                    f"${HA['ce']['H8/native_time']['mean_over_subjects']:.3f}$ & ${pd['mean_over_subjects']:+.3f}$ {fci(pd['ci95_subject_bootstrap'])} & "
                    f"${HA['accuracy']['C0/native_mean']['mean_over_subjects']:.3f}$ & ${HA['accuracy']['H8/native_mean']['mean_over_subjects']:.3f}$ & "
                    f"${HA['accuracy']['H8/native_time']['mean_over_subjects']:.3f}$ & ${HA['flip_vs_C0']['H8/native_mean']['mean_over_subjects']:.3f}$ \\\\")
        write("tab_har_subjects.tex", r"""\begin{table*}[t]
\caption{P1-HAR-01: one official TIDES classifier (one model seed) on UCI HAR inertial windows, per official test subject (windows overlap by 50\%, so the subject is the analysis unit). C0: the 128 distributed values as 128 held intervals of $1/50$\,s; H8: the first 64 intervals split by 8 (576 tokens), same held values and labels. CE: mean cross-entropy (nats) of the window label under token-mean pooling (official head) and time-weighted pooling of the same features (inference ablation). $d_s$: primary difference CE(mean, H8) $-$ CE(time, H8) per subject; the last row is the equal-weight mean over the 9 subjects with a subject-level paired percentile bootstrap interval (2000 draws), which is coarse with 9 clusters. acc.: accuracy. flip: fraction of windows whose predicted class under H8 (token mean) differs from C0.}
\label{tab:har-subjects}
\centering\small
\begin{tabular}{rrccccccccc}
\toprule
subject & windows & CE C0 & CE H8 mean & CE H8 time & $d_s$ & acc.\ C0 & acc.\ H8 mean & acc.\ H8 time & flip H8 mean \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table*}
""")
        rows = []
        arm_name = {"native_mean": "native, token mean", "native_time": "native, time-weighted", "resampled": "resampled (identity)"}
        for cn in ("S8", "H8"):
            for arm in ("native_mean", "native_time", "resampled"):
                kk = f"{cn}/{arm}"
                rc = HA["risk_change_vs_C0"][kk]
                rows.append(f"{cn} & {arm_name[arm]} & ${rc['mean_over_subjects']:+.4f}$ {fci(rc['ci95_subject_bootstrap'])} & "
                            f"${HA['flip_vs_C0'][kk]['mean_over_subjects']:.3f}$ & ${HA['tv_vs_C0'][kk]['mean_over_subjects']:.3f}$ & "
                            f"${HA['centered_logit_rel_vs_C0'][kk]['mean_over_subjects']:.3f}$ \\\\")
            if cn == "S8":
                rows.append(r"\midrule")
        write("tab_har_effects.tex", r"""\begin{table}[t]
\caption{P1-HAR-01 effects of the same-held-path refinement, equal-weight means over the 9 test subjects (subject means first). $\Delta$CE: cross-entropy of the arm on the condition minus cross-entropy of the official token-mean readout on C0, with the subject-level bootstrap interval. flip: fraction of windows whose predicted class differs from C0. TV: total variation $\tfrac12\sum_c|p_c-p_c^{\mathrm{C0}}|$ between the class probabilities. c.-logit: $\|\tilde z-\tilde z^{\mathrm{C0}}\|_2/\|\tilde z^{\mathrm{C0}}\|_2$ with class-centered logits (""" + str(HA["centered_logit_rel_vs_C0"]["excluded_windows"]) + r""" windows excluded by the $10^{-6}$ rule). The resampled arm reproduces the C0 input exactly (identity control).}
\label{tab:har-effects}
\centering\small
\begin{tabular}{llcccc}
\toprule
cond. & arm & $\Delta$CE vs.\ C0 [95\% CI] & flip & TV & c.-logit \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
""")
        trows = []
        for cn in ("C0", "S8", "H8"):
            tm = HA["timing"][cn]
            trows.append(f"{cn} & {tm['tokens_native']} & ${tm['native_end_to_end']['median_wall_s']:.3f}$ & ${tm['native_forward_only']['median_wall_s']:.3f}$ & "
                         f"${tm['resampled_end_to_end']['median_wall_s']:.3f}$ & ${tm['resampled_forward_only']['median_wall_s']:.3f}$ & ${tm['native_end_to_end']['median_cpu_s']:.2f}$ \\\\")
        write("tab_har_timing.tex", r"""\begin{table}[h]
\caption{P1-HAR-01 timing (one batch of the first 256 test windows; median of 5 timed calls after 2 warm-ups; \texttt{inference\_mode}; 2 threads). End-to-end includes tensor construction, LOCF resampling for the resampled arm, forward and pooling; forward-only is the model call on prebuilt tensors. CPU seconds are process CPU time summed over threads. Timed repeats are not independent samples.}
\label{tab:har-timing}
\centering\small
\begin{tabular}{rrccccc}
\toprule
cond. & tokens & nat.\ e2e & nat.\ fwd & res.\ e2e & res.\ fwd & nat.\ e2e CPU \\
\midrule
""" + "\n".join(trows) + r"""
\bottomrule
\end{tabular}
\end{table}
""")
        macros["HarD"] = f3(pd["mean_over_subjects"])
        macros["HarDlo"], macros["HarDhi"] = f3(pd["ci95_subject_bootstrap"][0]), f3(pd["ci95_subject_bootstrap"][1])
        macros["HarDmin"], macros["HarDmax"] = f3(pd["min"]), f3(pd["max"])
        macros["HarDpos"] = str(pd["n_positive"])
        macros["HarNsub"] = str(HA["n_subjects"])
        macros["HarNwin"] = str(HA["n_windows"])
        macros["HarCEczero"] = f"{HA['ce']['C0/native_mean']['mean_over_subjects']:.3f}"
        macros["HarAccCzero"] = f"{HA['accuracy']['C0/native_mean']['mean_over_subjects']:.3f}"
        macros["HarAccCzeroMin"] = f"{HA['accuracy']['C0/native_mean']['min']:.2f}"
        macros["HarAccCzeroMax"] = f"{HA['accuracy']['C0/native_mean']['max']:.2f}"
        for cn in ("S8", "H8"):
            for arm, nm in (("native_mean", "Mean"), ("native_time", "Time"), ("resampled", "Res")):
                kk = f"{cn}/{arm}"
                tag = ("Seight" if cn == "S8" else "Height") + nm
                macros[f"HarDCE{tag}"] = f3(HA["risk_change_vs_C0"][kk]["mean_over_subjects"])
                macros[f"HarDCE{tag}lo"] = f3(HA["risk_change_vs_C0"][kk]["ci95_subject_bootstrap"][0])
                macros[f"HarDCE{tag}hi"] = f3(HA["risk_change_vs_C0"][kk]["ci95_subject_bootstrap"][1])
                macros[f"HarFlip{tag}"] = f"{HA['flip_vs_C0'][kk]['mean_over_subjects']:.3f}"
                macros[f"HarTV{tag}"] = f"{HA['tv_vs_C0'][kk]['mean_over_subjects']:.3f}"
                macros[f"HarCL{tag}"] = f"{HA['centered_logit_rel_vs_C0'][kk]['mean_over_subjects']:.3f}"
                macros[f"HarAcc{tag}"] = f"{HA['accuracy'][kk]['mean_over_subjects']:.3f}"
        dec = HA["H8_logit_decomposition"]
        for key, nm in (("pmean_minus_pC0_norm", "Delta"), ("W_norm", "W"), ("M_norm", "M"), ("M_end_norm", "Mend"), ("Q_norm", "Q"), ("ptime_minus_pC0_norm", "Qt"), ("A_minus_B_norm", "AB")):
            macros[f"HarDec{nm}"] = f"{dec[key]['mean_over_subjects']:.3f}"
            macros[f"HarDec{nm}min"] = f"{dec[key]['min']:.3f}"
            macros[f"HarDec{nm}max"] = f"{dec[key]['max']:.3f}"
        macros["HarExcluded"] = str(HA["centered_logit_rel_vs_C0"]["excluded_windows"])
        nc = HA["numerical_checks"]
        macros["HarResIdent"] = sci(max(nc[f"{cn}_resampled_input_vs_C0_max_abs"] for cn in ("C0", "S8", "H8"))) if max(nc[f"{cn}_resampled_input_vs_C0_max_abs"] for cn in ("C0", "S8", "H8")) else "0"
        macros["HarPoolIdent"] = sci(nc["C0_native_mean_vs_native_time_max_abs"]) if nc["C0_native_mean_vs_native_time_max_abs"] else "0"
        macros["HarDecIdent"] = sci(max(HA["identity_checks"].values()))
        ck = HA["checkpoint"]
        macros["HarUpdate"] = str(ck["selected_update"])
        macros["HarUpdatesRun"] = str(ck["updates_run"])
        macros["HarCalCE"] = f"{ck['selected_cal_ce']:.3f}"
        macros["HarCalAcc"] = f"{ck['selected_cal_acc']:.3f}"
        macros["HarParams"] = f"{HT['n_parameters']:,}".replace(",", "{,}")
        macros["HarNfit"] = str(HT["n_fit_windows"])
        macros["HarNcal"] = str(HT["n_cal_windows"])
        if "control" in HA:
            ctl = HA["control"]
            macros["HarCtlCE"] = f"{ctl['C0']['ce_equal_weight_subjects']:.3f}"
            macros["HarCtlAcc"] = f"{ctl['C0']['acc_equal_weight_subjects']:.3f}"
            macros["HarCtlFeat"] = sci(max(ctl[cn]["max_abs_feature_diff_vs_C0"] for cn in ("S8", "H8")))
            macros["HarCtlCEdiff"] = sci(max(abs(ctl[cn]["ce_equal_weight_subjects"] - ctl["C0"]["ce_equal_weight_subjects"]) for cn in ("S8", "H8")))
        tm = HA["timing"]["S8"]
        macros["HarRatioSeight"] = f"{tm['native_end_to_end']['median_wall_s'] / tm['resampled_end_to_end']['median_wall_s']:.1f}"
        macros["HarFratioSeight"] = f"{tm['native_forward_only']['median_wall_s'] / tm['resampled_forward_only']['median_wall_s']:.1f}"
        tmh = HA["timing"]["H8"]
        macros["HarRatioHeight"] = f"{tmh['native_end_to_end']['median_wall_s'] / tmh['resampled_end_to_end']['median_wall_s']:.1f}"
        led = {r["stage"]: r for r in HL}
        macros["HarSmokeWall"] = f"{led['smoke']['wall_seconds']:.0f}" if "smoke" in led else "NA"
        macros["HarTrainWall"] = f"{led['train']['wall_seconds']:.0f}" if "train" in led else "NA"
        macros["HarTrainCPU"] = f"{led['train']['cpu_seconds']:.0f}" if "train" in led else "NA"
        macros["HarEvalWall"] = f"{led['eval']['wall_seconds']:.0f}" if "eval" in led else "NA"
        macros["HarTotalWall"] = f"{sum(r['wall_seconds'] for r in HL):.0f}"
        macros["HarTotalCPU"] = f"{sum(r['cpu_seconds'] for r in HL):.0f}"

    # ------------------------------------------------------------------ macros + json
    lines = [f"\\newcommand{{\\{k}}}{{\\ensuremath{{{v}}}}}" for k, v in sorted(macros.items())]
    write("numbers.tex", "\n".join(lines) + "\n")
    with open(os.path.join(ROOT, "results", "paper_assets.json"), "w") as f:
        json.dump(A, f, indent=1, default=str)


if __name__ == "__main__":
    main()
