"""Write paper/references.bib from paper/bib_provenance.json (arXiv abs-page metadata).

Only title, authors, year and arXiv id are used; no venue is asserted except the
arXiv journal-ref field when present, which is reported as such.
"""

import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KEYS = {
    "2111.00396": "gu2021s4", "2110.13985": "gu2021lssl", "2206.11893": "gu2022s4d", "2208.04933": "smith2022s5",
    "2312.00752": "gu2023mamba", "2405.21060": "dao2024mamba2", "2603.15569": "lahoti2026mamba3",
    "2605.09742": "soydan2026tides", "2402.19047": "cirone2024theoretical", "2005.08926": "kidger2020ncde",
    "2402.18512": "walker2024logncde", "2209.12951": "hasani2022liquid", "2210.06583": "nguyen2022s4nd",
    "2410.03464": "soydan2024s7", "2510.19003": "zhou2025dtmamba3d", "2410.03943": "rusch2024linoss",
    "2402.15584": "zubic2024event",
}


def main():
    prov = json.load(open(os.path.join(ROOT, "paper", "bib_provenance.json")))
    out = ["% AUTO-GENERATED by scripts/make_bib.py from paper/bib_provenance.json (arXiv abs-page metadata)."]
    for e in sorted(prov["entries"], key=lambda x: KEYS[x["id"]]):
        year = e["citation_date"][:4]
        title = e["title"]
        fields = [
            f"  title = {{{{{title}}}}}",
            f"  author = {{{' and '.join(e['authors'])}}}",
            f"  year = {{{year}}}",
            f"  eprint = {{{e['id']}}}",
            "  archivePrefix = {arXiv}",
            f"  howpublished = {{arXiv:{e['id']}}}",
        ]
        if e.get("journal_ref"):
            fields.append(f"  note = {{arXiv journal-ref: {e['journal_ref']}}}")
        out.append(f"@misc{{{KEYS[e['id']]},\n" + ",\n".join(fields) + "\n}")
    with open(os.path.join(ROOT, "paper", "references.bib"), "w") as f:
        f.write("\n\n".join(out) + "\n")


if __name__ == "__main__":
    main()
